<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CustomerNameDetail</name>
   <tag></tag>
   <elementGuidId>69cc44ea-c3c4-48d4-a724-bc18a3502521</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;NewApplication&quot;]/div/div[3]/span/div/div[2]/span/label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;NewApplication&quot;]/div/div[3]/span/div/div[2]/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;NewApplication&quot;]/div/div[3]/span/div/div[2]/span/label</value>
   </webElementProperties>
</WebElementEntity>
