<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Officer</name>
   <tag></tag>
   <elementGuidId>690a608e-e3be-4f4a-b97b-0c4ef5fb25a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;MOInfomation&quot;]/div[1]/label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;MOInfomation&quot;]/div[1]/label[1]</value>
   </webElementProperties>
</WebElementEntity>
