<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ReturnTo</name>
   <tag></tag>
   <elementGuidId>a6e2a4c5-efd9-47c8-b98c-af1ef7dfdb4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;formReturnCommission&quot;]/div[1]/div[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;formReturnCommission&quot;]/div[1]/div[2]/select</value>
   </webElementProperties>
</WebElementEntity>
