<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_ReturnNotes</name>
   <tag></tag>
   <elementGuidId>1b1c6788-88ab-45f0-b0c1-4c8968071965</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;formReturnCommission&quot;]/div[3]/div[2]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;formReturnCommission&quot;]/div[3]/div[2]/textarea</value>
   </webElementProperties>
</WebElementEntity>
