<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SaveLookup</name>
   <tag></tag>
   <elementGuidId>a4f2ece3-afc6-4464-8737-2da8152759ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-search-cross-app/div/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-search-cross-app/div/div/div/button</value>
   </webElementProperties>
</WebElementEntity>
