<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelCMOOfficer</name>
   <tag></tag>
   <elementGuidId>bf9efbce-2b45-498d-866c-2fcd3ecadc4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;MOInfomation&quot;]/div[1]/div[1]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;MOInfomation&quot;]/div[1]/div[1]/label</value>
   </webElementProperties>
</WebElementEntity>
