<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_TotalDataCross</name>
   <tag></tag>
   <elementGuidId>3e9d2415-71b5-4414-b7f6-b38e16f582bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//lib-ucgridfooter/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//lib-ucgridfooter/div/div[3]</value>
   </webElementProperties>
</WebElementEntity>
