<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tablenodata</name>
   <tag></tag>
   <elementGuidId>da3ced43-0b36-4fe1-9230-502affb561d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;crossInfomation&quot;]/div[2]/table/tbody[1]/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;crossInfomation&quot;]/div[2]/table/tbody[1]/tr/td</value>
   </webElementProperties>
</WebElementEntity>
