<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CustomerCheckingStep</name>
   <tag></tag>
   <elementGuidId>8b577e04-33f4-428f-8066-6197790c993f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@name=&quot;A.CUST_CHECKING_STEP&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@name=&quot;A.CUST_CHECKING_STEP&quot;]</value>
   </webElementProperties>
</WebElementEntity>
