<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_AppNo</name>
   <tag></tag>
   <elementGuidId>d2f7fbaf-e2b0-4a94-980c-e8ef309eef1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@name=&quot;A.APP_NO&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@name=&quot;A.APP_NO&quot;]</value>
   </webElementProperties>
</WebElementEntity>
