<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_AgreementStep</name>
   <tag></tag>
   <elementGuidId>03dadae0-5d80-49df-87cf-296fb3adf4b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@name=&quot;B.AGRMNT_CURR_STEP&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@name=&quot;B.AGRMNT_CURR_STEP&quot;]</value>
   </webElementProperties>
</WebElementEntity>
