<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ProdOfferingName</name>
   <tag></tag>
   <elementGuidId>6da6a5ec-8ca9-47d8-8683-c69aacb2846a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@name=&quot;A.PROD_OFFERING_NAME&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@name=&quot;A.PROD_OFFERING_NAME&quot;]</value>
   </webElementProperties>
</WebElementEntity>
