<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_POName</name>
   <tag></tag>
   <elementGuidId>37480860-9a0d-4f6a-a4d8-6d004f3b72c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@name=&quot;a.PROD_OFFERING_NAME&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@name=&quot;a.PROD_OFFERING_NAME&quot;]</value>
   </webElementProperties>
</WebElementEntity>
