<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_appNo</name>
   <tag></tag>
   <elementGuidId>d8329fe6-f9af-4091-8b23-83440d2007ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@name=&quot;a.APP_NO&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@name=&quot;a.APP_NO&quot;]</value>
   </webElementProperties>
</WebElementEntity>
