<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DiffRateAmt</name>
   <tag></tag>
   <elementGuidId>76632b1e-2ca7-469b-920c-3d58dc32c576</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;FinData_FinData&quot;]/form/div[1]/div[11]/div/div/div[4]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;FinData_FinData&quot;]/form/div[1]/div[11]/div/div/div[4]/input</value>
   </webElementProperties>
</WebElementEntity>
