<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tablesubsidynodata</name>
   <tag></tag>
   <elementGuidId>21ee7229-5f20-4ae3-958b-20be2d784def</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;FinData_Subsidy&quot;]/div[2]/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;FinData_Subsidy&quot;]/div[2]/table/tbody/tr/td</value>
   </webElementProperties>
</WebElementEntity>
