<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CustNotif</name>
   <tag></tag>
   <elementGuidId>5c4003cc-f841-4ec9-b5fe-589f037ce274</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;AppsInfoId&quot;]/div/div[9]/span/div/div[2]/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;AppsInfoId&quot;]/div/div[9]/span/div/div[2]/span/label</value>
   </webElementProperties>
</WebElementEntity>
