<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ECOSEC</name>
   <tag></tag>
   <elementGuidId>2f8c3a42-8330-4dfd-81de-e6837457c65e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;RestructuringDataId&quot;]/div/div[4]/span/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;RestructuringDataId&quot;]/div/div[4]/span/div/div[2]</value>
   </webElementProperties>
</WebElementEntity>
