<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InterestType</name>
   <tag></tag>
   <elementGuidId>9f616402-342d-4a7b-be0f-96b07c5f749f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;AppsInfoId&quot;]/div/div[4]/span/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;AppsInfoId&quot;]/div/div[4]/span/div/div[2]</value>
   </webElementProperties>
</WebElementEntity>
