<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>JumlahAsset</name>
   <tag></tag>
   <elementGuidId>6b798bb3-3e0c-47c1-b4c0-ca451e5870b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;appAttrContent&quot;]/div[5]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;appAttrContent&quot;]/div[5]/div[2]</value>
   </webElementProperties>
</WebElementEntity>
