<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelCMORecommendation</name>
   <tag></tag>
   <elementGuidId>4a4bc9fb-b010-4b35-ab14-2de3e044da76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;SalesInfoId&quot;]/div/div[3]/span/div/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;SalesInfoId&quot;]/div/div[3]/span/div/div[1]</value>
   </webElementProperties>
</WebElementEntity>
