<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelCMONotes</name>
   <tag></tag>
   <elementGuidId>99320a20-6d17-44ba-9700-499e0bfa99c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;SalesInfoId&quot;]/div/div[4]/span/div/div[1]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;SalesInfoId&quot;]/div/div[4]/span/div/div[1]/label</value>
   </webElementProperties>
</WebElementEntity>
