<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MORecomm</name>
   <tag></tag>
   <elementGuidId>5a4d91af-74ab-4619-889e-2ee3816a9b1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;SalesInfoId&quot;]/div/div[3]/span/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;SalesInfoId&quot;]/div/div[3]/span/div/div[2]</value>
   </webElementProperties>
</WebElementEntity>
