<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>REFMASTERAPPDATA</name>
   <tag></tag>
   <elementGuidId>58603b13-71c1-4d3c-b61d-5b6de5b07699</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;appAttrContent&quot;]/div[4]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;appAttrContent&quot;]/div[4]/div[2]</value>
   </webElementProperties>
</WebElementEntity>
