<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SPV</name>
   <tag></tag>
   <elementGuidId>62e14864-429c-4c0d-88d1-9fa3e8c8b54b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;SalesInfoId&quot;]/div/div[2]/span/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;SalesInfoId&quot;]/div/div[2]/span/div/div[2]</value>
   </webElementProperties>
</WebElementEntity>
