<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WOP</name>
   <tag></tag>
   <elementGuidId>e2828e56-ae8d-43d6-bb1b-fdc41750c69e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;AppsInfoId&quot;]/div/div[10]/span/div/div[2]/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;AppsInfoId&quot;]/div/div[10]/span/div/div[2]/span/label</value>
   </webElementProperties>
</WebElementEntity>
