<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WOR</name>
   <tag></tag>
   <elementGuidId>5e505d2e-9a53-4ed4-a3a0-65075a21e767</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;RestructuringDataId&quot;]/div/div[3]/span/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;RestructuringDataId&quot;]/div/div[3]/span/div/div[2]</value>
   </webElementProperties>
</WebElementEntity>
