<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_GenderSelect</name>
   <tag></tag>
   <elementGuidId>b18c16be-fb36-45c6-805a-4cfcdc491c68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CcMain']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-6</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GenderSelect One Female  Male Job PositionSelect One BENDAHARA ORGANISASI  BINTARA  BINTARA TINGGI  Director  DIREKTUR  GENERAL MANAGER / DIV. HEAD  GOLONGAN 1  GOLONGAN 2  GOLONGAN 3  GOLONGAN 4  KETUA ORGANISASI  KOMISARIS  KOMISARIS UTAMA  Manager  MANAGER / DEPT. HEAD  OTHER  Owner  OWNER (PEMILIK USAHA)  PERWIRA MENENGAH  PERWIRA PERTAMA  PERWIRA TINGGI  PRESIDEN DIREKTUR  SEKRETARIS ORGANISASI  STAFF  SUPERVISOR / SECTION HEAD  TAMTAMA  WAKIL KETUA ORGANISASI  WAKIL PRESIDEN DIREKTUR Birth PlaceBirth DateContact RelationshipSelect One Brother  Father  Mother  Other  Sister  Spouse Mobile Phone 2Email 2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CcMain&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CcMain']/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email 1'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile Phone 1'])[1]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
