<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_positionSLIK</name>
   <tag></tag>
   <elementGuidId>525f9b3f-5974-4114-b469-427c6b6f2849</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;CustMainData&quot;]/div[3]/div[1]/div/div/lib-uclookupgeneric/div/div/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;CustMainData&quot;]/div[3]/div[1]/div/div/lib-uclookupgeneric/div/div/input</value>
   </webElementProperties>
</WebElementEntity>
