<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelProffesion</name>
   <tag></tag>
   <elementGuidId>d6047340-3942-47c3-99f3-80a8afce8651</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;CustMainData&quot;]/div[2]/div[11]/div[2]/div/lib-uclookupgeneric/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;CustMainData&quot;]/div[2]/div[11]/div[2]/div/lib-uclookupgeneric/div/div/input</value>
   </webElementProperties>
</WebElementEntity>
