<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_RemainingInfoAmt</name>
   <tag></tag>
   <elementGuidId>15b231f4-5135-43aa-a08b-26857e3add6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;viewRemainIncomeInfo&quot;]/div[1]/div/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;viewRemainIncomeInfo&quot;]/div[1]/div/div[2]/label</value>
   </webElementProperties>
</WebElementEntity>
