<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_assettype</name>
   <tag></tag>
   <elementGuidId>bbed4c53-6750-4d5d-9f19-c5cd3b41c95b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;CustomerAssetSection&quot;]/div[2]/table/tbody/tr/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;CustomerAssetSection&quot;]/div[2]/table/tbody/tr/td[1]</value>
   </webElementProperties>
</WebElementEntity>
