<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Building</name>
   <tag></tag>
   <elementGuidId>4c51295a-bcbd-457c-9d20-5ff9c6b0b338</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;attrList&quot;]/div[9]/label[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;attrList&quot;]/div[9]/label[2]/span</value>
   </webElementProperties>
</WebElementEntity>
