<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CustomerName</name>
   <tag></tag>
   <elementGuidId>86fba6a3-724a-4e0d-a493-61f1fc91ea74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;CustPersonalMainDataId&quot;]/div/div[1]/span/div/div[2]/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;CustPersonalMainDataId&quot;]/div/div[1]/span/div/div[2]/span/label</value>
   </webElementProperties>
</WebElementEntity>
