<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InscoBranchName</name>
   <tag></tag>
   <elementGuidId>39a782d4-8bcf-4b07-be3f-cc23f76317dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/ngb-modal-window/div/div/app-app-insurance-detail/div[2]/div/div[2]/div[1]/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ngb-modal-window/div/div/app-app-insurance-detail/div[2]/div/div[2]/div[1]/label[2]</value>
   </webElementProperties>
</WebElementEntity>
