<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InsNote</name>
   <tag></tag>
   <elementGuidId>3ba59875-4c65-4883-a23d-92951a415770</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/ngb-modal-window/div/div/app-app-insurance-detail/div[2]/div/div[4]/div[1]/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ngb-modal-window/div/div/app-app-insurance-detail/div[2]/div/div[4]/div[1]/label[2]</value>
   </webElementProperties>
</WebElementEntity>
