<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Prev</name>
   <tag></tag>
   <elementGuidId>1340c8ea-1937-40b2-9c34-17f9fe5fcb5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@aria-label=&quot;Previous&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@aria-label=&quot;Previous&quot;]</value>
   </webElementProperties>
</WebElementEntity>
