<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>countData</name>
   <tag></tag>
   <elementGuidId>cd0e72e6-6fcb-4f2c-b5f8-5c1118723e54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//lib-ucgridfooter/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//lib-ucgridfooter/div/div[3]</value>
   </webElementProperties>
</WebElementEntity>
