<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_custNo</name>
   <tag></tag>
   <elementGuidId>7b3eaefb-acd0-4ffc-902f-71e1a64ac7f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table/thead/tr/th[5]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table/thead/tr/th[5]/span</value>
   </webElementProperties>
</WebElementEntity>
