<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Office</name>
   <tag></tag>
   <elementGuidId>88bee949-da38-4e14-84e9-b3b76ddb9631</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table/thead/tr/th[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table/thead/tr/th[3]/span</value>
   </webElementProperties>
</WebElementEntity>
