<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>discountamount</name>
   <tag></tag>
   <elementGuidId>522f9695-e21a-419f-bd86-01109ffd3646</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;SummaryCompanySection&quot;]/div[5]/div/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;SummaryCompanySection&quot;]/div[5]/div/label[2]</value>
   </webElementProperties>
</WebElementEntity>
