<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>insurancecompany</name>
   <tag></tag>
   <elementGuidId>d594573e-cf7d-4fca-9a16-0ba16293af30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;insuranceObject&quot;]/div[2]/div[1]/div[2]/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;insuranceObject&quot;]/div[2]/div[1]/div[2]/label[2]</value>
   </webElementProperties>
</WebElementEntity>
