<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>insurancelength</name>
   <tag></tag>
   <elementGuidId>5f4566bd-198e-4d40-ba9b-84edc5986235</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;insuranceObject&quot;]/div[2]/div[2]/div[3]/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;insuranceObject&quot;]/div[2]/div[2]/div[3]/label[2]</value>
   </webElementProperties>
</WebElementEntity>
