<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>totalfeefrominsco</name>
   <tag></tag>
   <elementGuidId>6b7ee460-4503-4e65-afc4-155b4b7bfd86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;SummaryCompanySection&quot;]/div[3]/div[2]/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;SummaryCompanySection&quot;]/div[3]/div[2]/label[2]</value>
   </webElementProperties>
</WebElementEntity>
