<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>totalpremifrominsco</name>
   <tag></tag>
   <elementGuidId>f9754155-98d6-441b-8c6e-64f1a66ababd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;SummaryCompanySection&quot;]/div[4]/div[2]/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;SummaryCompanySection&quot;]/div[4]/div[2]/label[2]</value>
   </webElementProperties>
</WebElementEntity>
