<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>totalmainpremitocustomer</name>
   <tag></tag>
   <elementGuidId>27fddc66-2b81-4854-b770-7759b373fc92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;SummaryCompanySection&quot;]/div[1]/div[1]/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;SummaryCompanySection&quot;]/div[1]/div[1]/label[2]</value>
   </webElementProperties>
</WebElementEntity>
