<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>custName</name>
   <tag></tag>
   <elementGuidId>115fef02-20e0-4831-ba6d-9c5221e6ff25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-full-layout/div/div[2]/div/div/div/div/app-return-handling-new-edit-app-paging/lib-ucpaging/lib-ucgridview/div/table/tbody/tr[1]/td[5]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-full-layout/div/div[2]/div/div/div/div/app-return-handling-new-edit-app-paging/lib-ucpaging/lib-ucgridview/div/table/tbody/tr[1]/td[5]/span</value>
   </webElementProperties>
</WebElementEntity>
