<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_nodataavailable</name>
   <tag></tag>
   <elementGuidId>350194bd-a077-49d0-8770-860a45b03efc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;CustomerAssetSection&quot;]/div[2]/table/tbody/tr/td</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;CustomerAssetSection&quot;]/div[2]/table/tbody/tr/td</value>
   </webElementProperties>
</WebElementEntity>
