<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AssetAttribute</name>
   <tag></tag>
   <elementGuidId>bcf3789f-1e25-4dc0-b009-067bfff540aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;RefAttrContent&quot;]/div[2]/div/div/div/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;RefAttrContent&quot;]/div[2]/div/div/div/div/select</value>
   </webElementProperties>
</WebElementEntity>
