<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Serial5</name>
   <tag></tag>
   <elementGuidId>85df047f-baa1-41ad-90c5-c40e6c04fd6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;assetData&quot;]/div[1]/div[8]/div/div[5]/div/div/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;assetData&quot;]/div[1]/div[8]/div/div[5]/div/div/input</value>
   </webElementProperties>
</WebElementEntity>
