<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Serial4</name>
   <tag></tag>
   <elementGuidId>1c4addb2-d7dc-4a62-8265-03f4a66d6623</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[9]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;assetData&quot;]/div[1]/div[8]/div/div[4]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;assetData&quot;]/div[1]/div[8]/div/div[4]/div/div/input</value>
   </webElementProperties>
</WebElementEntity>
