<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Serial4_FL4W</name>
   <tag></tag>
   <elementGuidId>644e59c9-d1bb-4dc8-9e91-a54e8dcf2edc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;assetInfo&quot;]/div[1]/div[8]/div/div[4]/div/div/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;assetInfo&quot;]/div[1]/div[8]/div/div[4]/div/div/input</value>
   </webElementProperties>
</WebElementEntity>
