<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelKelurahanAssetOwner</name>
   <tag></tag>
   <elementGuidId>8b0b5bf8-efc0-4520-b4dd-dafc713c9689</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ownerData&quot;]/div/div[2]/div/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ownerData&quot;]/div/div[2]/div/div[2]/div/input</value>
   </webElementProperties>
</WebElementEntity>
