<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelZipcodeAssetOwnerCF4W</name>
   <tag></tag>
   <elementGuidId>b606d143-cd83-4106-9ed9-0bb616af5fc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ownerData&quot;]/div/div[2]/div/div[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ownerData&quot;]/div/div[2]/div/div[1]/div/input</value>
   </webElementProperties>
</WebElementEntity>
