<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_totalSupplier</name>
   <tag></tag>
   <elementGuidId>7da9b39d-026c-408f-a3c4-bc0ab611404e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//lib-ucgridfooter/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//lib-ucgridfooter/div/div[3]</value>
   </webElementProperties>
</WebElementEntity>
