<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonDelete</name>
   <tag></tag>
   <elementGuidId>71a13d65-b36b-476b-814b-acd5176b2697</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;crossInfomation&quot;]/div[2]/table/tbody/tr[1]/td[4]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;crossInfomation&quot;]/div[2]/table/tbody/tr[1]/td[4]/a/i</value>
   </webElementProperties>
</WebElementEntity>
