<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_DeleteCross</name>
   <tag></tag>
   <elementGuidId>7148239a-3ec0-4fef-b1d4-a0340441ca17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;crossInfomation&quot;]/div[2]/table/tbody/tr[1]/td[4]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;crossInfomation&quot;]/div[2]/table/tbody/tr[1]/td[4]/a/i</value>
   </webElementProperties>
</WebElementEntity>
