<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelZipcode</name>
   <tag></tag>
   <elementGuidId>a0cac678-b1a8-4cda-a017-43d58eee9ade</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;Address&quot;]/div/div[1]/div[3]/div[1]/div/lib-uclookupgeneric/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;Address&quot;]/div/div[1]/div[3]/div[1]/div/lib-uclookupgeneric/div/div/input</value>
   </webElementProperties>
</WebElementEntity>
