<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelCMOSupervisor</name>
   <tag></tag>
   <elementGuidId>a322014e-34dc-475e-b9e0-b104c7aeb363</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;MOInfomation&quot;]/div[1]/label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;MOInfomation&quot;]/div[1]/label[1]</value>
   </webElementProperties>
</WebElementEntity>
