<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modifyCross</name>
   <tag></tag>
   <elementGuidId>e30b847d-5b89-450c-9833-d7b9a38e20d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;crossInfomation&quot;]/div[2]/table/tbody/tr[1]/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;crossInfomation&quot;]/div[2]/table/tbody/tr[1]/td[1]</value>
   </webElementProperties>
</WebElementEntity>
