<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonedit</name>
   <tag></tag>
   <elementGuidId>325a20dc-cfb2-481f-a616-9f1a7f65aee3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;CustomerAssetSection&quot;]/div[2]/table/tbody/tr/td[6]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;CustomerAssetSection&quot;]/div[2]/table/tbody/tr/td[6]/a/i</value>
   </webElementProperties>
</WebElementEntity>
