<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_TotalPremium</name>
   <tag></tag>
   <elementGuidId>1930bb20-eaa4-4ba3-9708-e2a571edd52c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;insuranceInformation&quot;]/div[3]/lib-ucsubsection[3]/div/form/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;insuranceInformation&quot;]/div[3]/lib-ucsubsection[3]/div/form/div/h4</value>
   </webElementProperties>
</WebElementEntity>
