<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SaveMain</name>
   <tag></tag>
   <elementGuidId>b9c7c6c3-b746-4b5a-ae4b-36d0dfdfdbb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;insurance-tab&quot;]/app-insurance-multi-asset-data/app-uc-insurance/div/div/div/div/div/form/div[2]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;insurance-tab&quot;]/app-insurance-multi-asset-data/app-uc-insurance/div/div/div/div/div/form/div[2]/button[2]</value>
   </webElementProperties>
</WebElementEntity>
