<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FullCapitalizedAmount</name>
   <tag></tag>
   <elementGuidId>b682fefd-af12-4d08-91b5-c89485a80a71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;totalPremi&quot;]/div[7]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;totalPremi&quot;]/div[7]/div/input</value>
   </webElementProperties>
</WebElementEntity>
