<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modifyObjectMultiple</name>
   <tag></tag>
   <elementGuidId>0c5c8a22-22ff-4f63-b507-194be1c5a0f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;collateral&quot;]/lib-ucgridview/div/table/tbody/tr[1]/td[10]/span/span/span/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;collateral&quot;]/lib-ucgridview/div/table/tbody/tr[1]/td[10]/span/span/span/a/i</value>
   </webElementProperties>
</WebElementEntity>
