<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SumInsuredAmountTerrorist</name>
   <tag></tag>
   <elementGuidId>4afca52e-5b5f-4d12-8fc8-9dd3cbf411f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='insuranceCoverage']/div[5]/table/tbody/tr[9]/td[7]/div/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='insuranceCoverage']/div[5]/table/tbody/tr[9]/td[7]/div/div/select</value>
   </webElementProperties>
</WebElementEntity>
