<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TotalDiscountAmount</name>
   <tag></tag>
   <elementGuidId>eafccded-b837-468a-9907-cc7cdc6132c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;summaryInsurance&quot;]/div[2]/div/label[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;summaryInsurance&quot;]/div[2]/div/label[4]</value>
   </webElementProperties>
</WebElementEntity>
