<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_AddCollateral</name>
   <tag></tag>
   <elementGuidId>06527b14-d6d2-46f6-989d-153cdef7e47d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;asset-tab&quot;]/app-multi-asset-data/div/app-asset-data-paging/div[4]/span/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;asset-tab&quot;]/app-multi-asset-data/div/app-asset-data-paging/div[4]/span/button/span</value>
   </webElementProperties>
</WebElementEntity>
