<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SaveMain</name>
   <tag></tag>
   <elementGuidId>e7bf2649-dc7b-4ed2-b636-d865110a777b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;asset-tab&quot;]/app-multi-asset-data/div/app-asset-data-paging/div[6]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;asset-tab&quot;]/app-multi-asset-data/div/app-asset-data-paging/div[6]/button[2]</value>
   </webElementProperties>
</WebElementEntity>
