<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_OwnerProfession</name>
   <tag></tag>
   <elementGuidId>b9f4e106-4ffa-422e-b3b8-2683599f2666</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;AddCollOwner&quot;]/div[4]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;AddCollOwner&quot;]/div[4]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
