<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Radio_Company</name>
   <tag></tag>
   <elementGuidId>8127d78d-d360-485c-91c7-2eb84200dac1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-full-layout/div/div[2]/div/div/div/div/app-nap-detail-form/div/div/div[2]/div/div[1]/div[2]/div[3]/app-multi-asset-data/div/app-collateral-add-edit/div/div/div[2]/form/div/div[2]/div[3]/div[1]/div[2]/mat-radio-group/mat-radio-button[1]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-full-layout/div/div[2]/div/div/div/div/app-nap-detail-form/div/div/div[2]/div/div[1]/div[2]/div[3]/app-multi-asset-data/div/app-collateral-add-edit/div/div/div[2]/form/div/div[2]/div[3]/div[1]/div[2]/mat-radio-group/mat-radio-button[1]/label</value>
   </webElementProperties>
</WebElementEntity>
