<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_RemainingAllocatedAmt</name>
   <tag></tag>
   <elementGuidId>c010e0b4-0a43-4315-9858-6689b9a39c0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;viewRemainIncomeInfo&quot;]/div[9]/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;viewRemainIncomeInfo&quot;]/div[9]/div[2]/label</value>
   </webElementProperties>
</WebElementEntity>
