<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_IncomeInfoAmt</name>
   <tag></tag>
   <elementGuidId>db83863e-9597-4338-9305-7f4d7028a472</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;viewIncomeInfo&quot;]/div[1]/div/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;viewIncomeInfo&quot;]/div[1]/div/div[2]/label</value>
   </webElementProperties>
</WebElementEntity>
