<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_RemainingInfo</name>
   <tag></tag>
   <elementGuidId>9b358ed5-9542-436e-8f93-55bea3a02a13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;viewRemainIncomeInfo&quot;]/div[1]/div/div[1]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;viewRemainIncomeInfo&quot;]/div[1]/div/div[1]/label</value>
   </webElementProperties>
</WebElementEntity>
