<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_appNo</name>
   <tag></tag>
   <elementGuidId>81c2120a-1978-489c-b1d2-2cc082915846</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;NewApplication&quot;]/div/div[1]/span/div/div[2]/label/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;NewApplication&quot;]/div/div[1]/span/div/div[2]/label/a/span</value>
   </webElementProperties>
</WebElementEntity>
