<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonAddAsset</name>
   <tag></tag>
   <elementGuidId>bf1341eb-42bd-4a45-bbb7-51b09c104c2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;asset-tab&quot;]/app-multi-asset-data/div/app-asset-data-paging/div[1]/span/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;asset-tab&quot;]/app-multi-asset-data/div/app-asset-data-paging/div[1]/span/button</value>
   </webElementProperties>
</WebElementEntity>
