<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_RSVAllocFrom</name>
   <tag></tag>
   <elementGuidId>8d578f51-ecdd-4f54-be65-1391980b71c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;reserved-fund-tab&quot;]/reserved-fund/div/div/div/form/div/div[1]/div[1]/lib-ucsubsection/div/form/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;reserved-fund-tab&quot;]/reserved-fund/div/div/div/form/div/div[1]/div[1]/lib-ucsubsection/div/form/div/h4</value>
   </webElementProperties>
</WebElementEntity>
