<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SumInsuredAmountSRCC</name>
   <tag></tag>
   <elementGuidId>12a97534-0551-4e17-a748-990cae64e5c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='insuranceCoverage']/div[5]/table/tbody/tr[6]/td[7]/div/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='insuranceCoverage']/div[5]/table/tbody/tr[6]/td[7]/div/div/select</value>
   </webElementProperties>
</WebElementEntity>
