<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_AppNo</name>
   <tag></tag>
   <elementGuidId>1b1f59ec-d0bc-4989-acb0-cd5a0f4aa6b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;NewApplication&quot;]/div/div[1]/span/div/div[2]/label/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;NewApplication&quot;]/div/div[1]/span/div/div[2]/label/a/span</value>
   </webElementProperties>
</WebElementEntity>
