<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>enddate</name>
   <tag></tag>
   <elementGuidId>e06eb30f-d680-42a8-9f4d-b1b258a94150</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;insuranceObject&quot;]/div/div[2]/div[4]/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;insuranceObject&quot;]/div/div[2]/div[4]/label[2]</value>
   </webElementProperties>
</WebElementEntity>
