<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SelectApplicationInProcessPersonal</name>
   <tag></tag>
   <elementGuidId>38d93561-d8ec-4c68-b22f-6406bca93a80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;subSecAppProcess&quot;]/table/tbody/tr[1]/td[5]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;subSecAppProcess&quot;]/table/tbody/tr[1]/td[10]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;subSecAppProcess&quot;]/table/tbody/tr[1]/td[10]/a</value>
   </webElementProperties>
</WebElementEntity>
