<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_NegativePersonal</name>
   <tag></tag>
   <elementGuidId>f0ce3569-0c26-4ef6-bd7d-160af2260555</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-full-layout/div/div[2]/div/div/div/div/app-dup-check-md-subj-match/div/div[2]/div[3]/table/tbody/tr[1]/td[11]/mat-checkbox/label/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-full-layout/div/div[2]/div/div/div/div/app-dup-check-md-subj-match/div/div[2]/div[3]/table/tbody/tr[1]/td[11]/mat-checkbox/label/span[1]</value>
   </webElementProperties>
</WebElementEntity>
