<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_NoDataFoundAppInProcess</name>
   <tag></tag>
   <elementGuidId>054e762d-de59-4194-bdc3-8d61dedb1f8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;subSecAppProcess&quot;]/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;subSecAppProcess&quot;]/table/tbody/tr/td</value>
   </webElementProperties>
</WebElementEntity>
