<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_NoDataFoundSimilardata</name>
   <tag></tag>
   <elementGuidId>f6f38b41-89e5-472a-8a52-d2d44ca5adc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;subSecMatch&quot;]/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;subSecMatch&quot;]/table/tbody/tr/td</value>
   </webElementProperties>
</WebElementEntity>
