<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Office</name>
   <tag></tag>
   <elementGuidId>a08899e8-ae0b-414e-9c0f-74694b549202</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@name=&quot;a.ORI_OFFICE_NAME&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@name=&quot;a.ORI_OFFICE_NAME&quot;]</value>
   </webElementProperties>
</WebElementEntity>
