<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tr_ApplicantNoApplicationInProcess</name>
   <tag></tag>
   <elementGuidId>2879e53a-48be-4615-9850-574326e5852a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;subSecAppProcess&quot;]/table/tbody/tr[1]/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;subSecAppProcess&quot;]/table/tbody/tr[1]/td[1]</value>
   </webElementProperties>
</WebElementEntity>
