<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LabelZipcode</name>
   <tag></tag>
   <elementGuidId>38e155cc-b063-426b-986f-af1df9857985</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;UcAddress&quot;]/div/div[2]/div/div[1]/div/lib-uclookupgeneric/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;UcAddress&quot;]/div/div[2]/div/div[1]/div/lib-uclookupgeneric/div/div/input</value>
   </webElementProperties>
</WebElementEntity>
