<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SaveExistinCol</name>
   <tag></tag>
   <elementGuidId>985aff87-c97c-481b-a537-e808c2e4515c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;asset-tab&quot;]/app-multi-asset-data/div/app-collateral-add-edit/div/div/div[2]/form/div/div[2]/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;asset-tab&quot;]/app-multi-asset-data/div/app-collateral-add-edit/div/div/div[2]/form/div/div[2]/div[3]/button[2]</value>
   </webElementProperties>
</WebElementEntity>
