<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Custno</name>
   <tag></tag>
   <elementGuidId>4ce43764-1ca9-467c-b1b4-927f7d86ecb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;NewApplication&quot;]/div/div[3]/span/div/div[2]/span/span[1]/span/span/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;NewApplication&quot;]/div/div[3]/span/div/div[2]/span/span[1]/span/span/span/a</value>
   </webElementProperties>
</WebElementEntity>
