<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AssetAttribute</name>
   <tag></tag>
   <elementGuidId>db1fd5fb-a642-4e0b-a06f-9d946c4662c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;RefAttrContent&quot;]/div[2]/div/div/div/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;RefAttrContent&quot;]/div[2]/div/div/div/div/select</value>
   </webElementProperties>
</WebElementEntity>
