<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AdditionalPremi</name>
   <tag></tag>
   <elementGuidId>0aaede0d-3c33-44d5-996f-023a4102bff3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;InsuranceObjectSection&quot;]/div/table/tbody/tr/td[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;InsuranceObjectSection&quot;]/div/table/tbody/tr/td[9]</value>
   </webElementProperties>
</WebElementEntity>
