<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ButtonViewDetail</name>
   <tag></tag>
   <elementGuidId>6f1e4903-86ed-41f4-bb02-ec0d771c0b23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;InsuranceObjectSection&quot;]/div/table/tbody/tr/td[11]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;InsuranceObjectSection&quot;]/div/table/tbody/tr/td[11]/a/i</value>
   </webElementProperties>
</WebElementEntity>
