<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InsuredBy</name>
   <tag></tag>
   <elementGuidId>19aea29a-4b9a-415a-ba7b-4a58a9b4f1ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;InsuranceObjectSection&quot;]/div/table/tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;InsuranceObjectSection&quot;]/div/table/tbody/tr/td[2]</value>
   </webElementProperties>
</WebElementEntity>
