<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PaidAmountByCust</name>
   <tag></tag>
   <elementGuidId>8f00d8e9-b484-40d0-87b8-553424f72fad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-tab-content-0-5&quot;]/div/view-insurance/div[2]/div/div[1]/div[2]/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-tab-content-0-5&quot;]/div/view-insurance/div[2]/div/div[1]/div[2]/label[2]</value>
   </webElementProperties>
</WebElementEntity>
