<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PaymentType</name>
   <tag></tag>
   <elementGuidId>c0bab47c-1671-4bad-9a45-558b98380b03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;InsuranceObjectSection&quot;]/div/table/tbody/tr/td[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;InsuranceObjectSection&quot;]/div/table/tbody/tr/td[5]</value>
   </webElementProperties>
</WebElementEntity>
