<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TotalPremiToCust</name>
   <tag></tag>
   <elementGuidId>2b23a9c5-ec3a-4ea5-abf8-4582831361c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-tab-content-0-5&quot;]/div/view-insurance/div[2]/div/div[1]/div[1]/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-tab-content-0-5&quot;]/div/view-insurance/div[2]/div/div[1]/div[1]/label[2]</value>
   </webElementProperties>
</WebElementEntity>
