<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LabelCountryLookup</name>
   <tag></tag>
   <elementGuidId>23e97be3-7c37-4256-aad7-db7b21639395</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;CustMainData&quot;]/div[2]/div[12]/div[2]/div[2]/lib-uclookupgeneric/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;CustMainData&quot;]/div[2]/div[12]/div[2]/div[2]/lib-uclookupgeneric/div/div/input</value>
   </webElementProperties>
</WebElementEntity>
