<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download</name>
   <tag></tag>
   <elementGuidId>b7c139ab-6366-4c33-af3c-e65b2bc42d64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//lib-ucgridview/div/table/tbody/tr[1]/td[5]/span/span/span/a[@class=&quot;success&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//lib-ucgridview/div/table/tbody/tr[1]/td[5]/span/span/span/a[@class=&quot;success&quot;]</value>
   </webElementProperties>
</WebElementEntity>
