<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_RuleFile</name>
   <tag></tag>
   <elementGuidId>fb7a5fa5-5b89-4d1d-a973-5fe60f782d71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href=&quot;/Rule_R3_FE/rule-files/paging&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@href=&quot;/Rule_R3_FE/rule-files/paging&quot;]</value>
   </webElementProperties>
</WebElementEntity>
