<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CustomerModelCode</name>
   <tag></tag>
   <elementGuidId>f391df98-14a0-4039-a7c1-7061d85a45d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;NewApplication&quot;]/div/div[13]/span/div/div[2]/span/label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;NewApplication&quot;]/div/div[13]/span/div/div[2]/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;NewApplication&quot;]/div/div[13]/span/div/div[2]/span/label</value>
   </webElementProperties>
</WebElementEntity>
