package dbconnection

import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import static com.kms.katalon.core.testobject.ObjectRepository.findWindowsObject

import com.kms.katalon.core.annotation.Keyword
import com.kms.katalon.core.checkpoint.Checkpoint
import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling
import com.kms.katalon.core.testcase.TestCase
import com.kms.katalon.core.testdata.TestData
import com.kms.katalon.core.testobject.TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import com.kms.katalon.core.windows.keyword.WindowsBuiltinKeywords as Windows

import groovy.sql.Sql
import internal.GlobalVariable

public class CustomerDataVerif {

	@Keyword
	public CustomerDataPersonal (Sql instance, String name, String idtype, String custmodel){
		String customerdata
		instance.eachRow(("select DISTINCT Cust_name AS HEADER, BIRTH_PLACE AS HEADER, MR_ID_TYPE_CODE AS HEADER, ID_EXPIRED_DT AS HEADER, MR_MARITAL_STAT_CODE AS HEADER, MOBILE_PHN_NO_1 AS HEADER, MR_CUST_MODEL_CODE AS HEADER, MR_GENDER_CODE AS HEADER, FORMAT(BIRTH_DT, 'yyyy-MM-dd') AS HEADER, ID_NO AS HEADER, TAX_ID_NO AS HEADER, MOTHER_MAIDEN_NAME AS HEADER, EMAIL_1 AS HEADER, ADDR AS HEADER, AREA_CODE_4 AS HEADER, AREA_CODE_3 AS HEADER, ZIPCODE AS HEADER, AREA_CODE_2 AS HEADER, AREA_CODE_1 AS HEADER, CITY AS HEADER, MR_BUILDING_OWNERSHIP_CODE AS HEADER from cust a join cust_addr b on a.CUST_ID = b.CUST_ID JOIN cust_personal c on a.cust_ID = c.CUST_ID where a.cust_name = '"+ name +"' and MR_ID_TYPE_CODE = '"+ idtype +"' AND MR_CUST_MODEL_CODE = '"+ custmodel + "' AND MR_CUST_ADDR_TYPE_CODE = 'legal'"), {  row ->

			customerdata = (row)
		})
		return customerdata
	}

	@Keyword
	public CustomerDataCompany (Sql instance, String name, String companytype){
		String customerdata
		instance.eachRow(("select DISTINCT Cust_name AS HEADER, TAX_ID_NO AS HEADER, MR_COMPANY_TYPE_CODE AS HEADER ,MR_CUST_MODEL_CODE AS HEADER, ADDR AS HEADER, AREA_CODE_4 AS HEADER, AREA_CODE_3 AS HEADER, ZIPCODE AS HEADER, AREA_CODE_2 AS HEADER, AREA_CODE_1 AS HEADER, CITY AS HEADER, MR_BUILDING_OWNERSHIP_CODE AS HEADER from cust a join cust_addr b on a.CUST_ID = b.CUST_ID JOIN CUST_COMPANY c on a.cust_ID = c.CUST_ID where a.cust_name = '"+ name +"' AND MR_COMPANY_TYPE_CODE = '"+ companytype +"' AND MR_CUST_ADDR_TYPE_CODE = 'legal'"), {  row ->

			customerdata = (row)
		})
		return customerdata
	}

	@Keyword
	public FamilyDataPersonal (Sql instance, String name, String idno){
		String customerdata
		instance.eachRow(("select Cust_name AS HEADER, BIRTH_PLACE AS HEADER, MR_ID_TYPE_CODE AS HEADER, ID_EXPIRED_DT AS HEADER, MR_MARITAL_STAT_CODE AS HEADER, MOBILE_PHN_NO_1 AS HEADER, MR_CUST_MODEL_CODE AS HEADER, MR_GENDER_CODE AS HEADER, FORMAT(BIRTH_DT, 'yyyy-MM-dd') AS HEADER, ID_NO AS HEADER, TAX_ID_NO AS HEADER, MOTHER_MAIDEN_NAME AS HEADER, EMAIL_1 AS HEADER, MR_NATIONALITY_CODE AS HEADER, UPPER(COUNTRY_NAME) AS HEADER, ADDR AS HEADER, AREA_CODE_4 AS HEADER, AREA_CODE_3 AS HEADER, ZIPCODE AS HEADER, AREA_CODE_2 AS HEADER, AREA_CODE_1 AS HEADER, CITY AS HEADER, MR_BUILDING_OWNERSHIP_CODE AS HEADER from cust a join cust_addr b on a.CUST_ID = b.CUST_ID join cust_personal c on a.cust_ID = c.CUST_ID join REF_COUNTRY d on c.WNA_COUNTRY_CODE = d.COUNTRY_CODE where a.cust_name = '"+ name + "' AND ID_NO = '"+ idno +"' AND MR_CUST_ADDR_TYPE_CODE = 'legal'"), {  row ->

			customerdata = (row)
		})
		return customerdata
	}

	@Keyword
	public CheckCustomerExisting (Sql instance, String appno){
		int checkresult
		instance.eachRow(("USE LOS SELECT COUNT(IS_EXISTING_CUST) FROM APP_CUST a JOIN APP b on a.APP_ID = b.APP_ID WHERE APP_NO = '"+ appno + "' and IS_CUSTOMER = 1"), {  row ->

			checkresult = (row[0])
		})
		return checkresult
	}

	@Keyword
	public CustomerStoreDataPersonal (Sql instance, String appno){
		String customerdata
		instance.eachRow(("SELECT b.PROD_OFFERING_CODE AS HEADER, Cust_name AS HEADER, BIRTH_PLACE AS HEADER, MR_ID_TYPE_CODE AS HEADER, FORMAT(ID_EXPIRED_DT, 'MM/dd/yyyy') AS HEADER, MR_MARITAL_STAT_CODE AS HEADER, MOBILE_PHN_NO_1 AS HEADER, f.REF_MASTER_NAME AS HEADER, MR_GENDER_CODE AS HEADER, FORMAT(BIRTH_DT, 'MM/dd/yyyy') AS HEADER, ID_NO AS HEADER, TAX_ID_NO AS HEADER, MOTHER_MAIDEN_NAME AS HEADER, EMAIL_1 AS HEADER, e.ATTR_VALUE AS HEADER, SUBQ.ATTR_VALUE AS HEADER, ADDR AS HEADER, AREA_CODE_4 AS HEADER, AREA_CODE_3 AS HEADER, ZIPCODE AS HEADER, AREA_CODE_2 AS HEADER, AREA_CODE_1 AS HEADER, CITY AS HEADER, g.REF_MASTER_NAME AS HEADER FROM APP_CUST a JOIN app b ON a.APP_ID = b.APP_ID JOIN APP_CUST_PERSONAL c ON a.APP_CUST_ID = c.APP_CUST_ID  JOIN APP_CUST_ADDR d ON a.APP_CUST_ID = d.APP_CUST_ID JOIN APP_CUST_ATTR_CONTENT e ON e.APP_CUST_ID = a.APP_CUST_ID JOIN REF_MASTER_LOS f ON a.MR_CUST_MODEL_CODE = f.REF_MASTER_CODE JOIN REF_MASTER_LOS g ON d.MR_HOUSE_OWNERSHIP_CODE = g.REF_MASTER_CODE, (SELECT ATTR_VALUE, a.APP_ID FROM APP_CUST_ATTR_CONTENT g JOIN APP_CUST a ON g.APP_CUST_ID = a.APP_CUST_ID JOIN app b ON a.APP_ID = b.APP_ID WHERE APP_NO = '"+ appno +"'AND IS_CUSTOMER = 1 AND g.REF_ATTR_CODE = 'AUTH_AML') as SUBQ WHERE a.APP_ID = SUBQ.APP_ID AND IS_CUSTOMER = 1 AND MR_CUST_ADDR_TYPE_CODE = 'LEGAL' AND MR_CUST_TYPE_CODE = 'PERSONAL' AND e.REF_ATTR_CODE = 'AML_CUST_DEPARTMENT' AND f.REF_MASTER_TYPE_CODE = 'CUST_MODEL' AND g.REF_MASTER_TYPE_CODE = 'BUILDING_OWNERSHIP'"), {  row ->

			customerdata = (row)
		})
		return customerdata
	}

	@Keyword
	public FamilyStoreDataPersonal (Sql instance, String appno){
		String familydata
		instance.eachRow(("SELECT MR_CUST_RELATIONSHIP_CODE AS HEADER ,Cust_name AS HEADER, BIRTH_PLACE AS HEADER, g.REF_MASTER_NAME AS HEADER, FORMAT(ID_EXPIRED_DT, 'MM/dd/yyyy') AS HEADER, MR_MARITAL_STAT_CODE AS HEADER, MOBILE_PHN_NO_1 AS HEADER, h.REF_MASTER_NAME AS HEADER, e.MR_PROFESSION_CODE AS HEADER, FORMAT(e.ESTABLISHMENT_DT, 'MM/dd/yyyy') AS HEADER, MR_GENDER_CODE AS HEADER, FORMAT(BIRTH_DT, 'MM/dd/yyyy') AS HEADER, ID_NO AS HEADER, TAX_ID_NO AS HEADER, MOTHER_MAIDEN_NAME AS HEADER, EMAIL_1 AS HEADER, MR_NATIONALITY_CODE AS HEADER, NATIONALITY_COUNTRY_CODE AS HEADER, MR_JOB_POSITION_CODE AS HEADER, f.ATTR_VALUE AS HEADER, SUBQ.ATTR_VALUE AS HEADER, ADDR AS HEADER, AREA_CODE_4 AS HEADER, AREA_CODE_3 AS HEADER, ZIPCODE AS HEADER, AREA_CODE_2 AS HEADER, AREA_CODE_1 AS HEADER, CITY AS HEADER, i.REF_MASTER_NAME AS HEADER FROM APP_CUST a JOIN app b ON a.APP_ID = b.APP_ID JOIN APP_CUST_PERSONAL c ON a.APP_CUST_ID = c.APP_CUST_ID JOIN APP_CUST_ADDR d ON a.APP_CUST_ID = d.APP_CUST_ID JOIN APP_CUST_PERSONAL_JOB_DATA e ON c.APP_CUST_PERSONAL_ID = e.APP_CUST_PERSONAL_ID JOIN APP_CUST_ATTR_CONTENT f ON f.APP_CUST_ID = a.APP_CUST_ID JOIN REF_MASTER_LOS g ON a.MR_ID_TYPE_CODE = g.REF_MASTER_CODE JOIN REF_MASTER_LOS h ON a.MR_CUST_MODEL_CODE = h.REF_MASTER_CODE JOIN REF_MASTER_LOS i ON d.MR_HOUSE_OWNERSHIP_CODE = i.REF_MASTER_CODE, (SELECT ATTR_VALUE, a.APP_ID FROM APP_CUST_ATTR_CONTENT g JOIN APP_CUST a ON g.APP_CUST_ID = a.APP_CUST_ID JOIN app b ON a.APP_ID = b.APP_ID WHERE APP_NO = '"+ appno +"' AND IS_FAMILY = 1 AND g.REF_ATTR_CODE = 'AUTH_AML') as SUBQ where a.APP_ID = SUBQ.APP_ID AND IS_FAMILY = 1 AND MR_CUST_ADDR_TYPE_CODE = 'LEGAL' AND MR_CUST_TYPE_CODE = 'PERSONAL' AND f.REF_ATTR_CODE = 'AML_CUST_DEPARTMENT' AND g.REF_MASTER_TYPE_CODE = 'ID_TYPE' AND h.REF_MASTER_TYPE_CODE = 'CUST_MODEL' AND i.REF_MASTER_TYPE_CODE = 'BUILDING_OWNERSHIP'"), {  row ->

			familydata = (row)
		})
		return familydata
	}

	@Keyword
	public GuarantorStoreDataPersonal (Sql instance, String appno){
		String guarantordata
		instance.eachRow(("SELECT MR_CUST_RELATIONSHIP_CODE AS HEADER ,Cust_name AS HEADER, BIRTH_PLACE AS HEADER, f.REF_MASTER_NAME AS HEADER, FORMAT(ID_EXPIRED_DT, 'MM/dd/yyyy') AS HEADER, MR_MARITAL_STAT_CODE AS HEADER, MOBILE_PHN_NO_1 AS HEADER, g.REF_MASTER_NAME AS HEADER, MR_GENDER_CODE AS HEADER, FORMAT(BIRTH_DT, 'MM/dd/yyyy') AS HEADER, ID_NO AS HEADER, TAX_ID_NO AS HEADER, MOTHER_MAIDEN_NAME AS HEADER, EMAIL_1 AS HEADER, e.ATTR_VALUE AS HEADER, SUBQ.ATTR_VALUE AS HEADER, ADDR AS HEADER, AREA_CODE_4 AS HEADER, AREA_CODE_3 AS HEADER, ZIPCODE AS HEADER, AREA_CODE_2 AS HEADER, AREA_CODE_1 AS HEADER, CITY AS HEADER, h.REF_MASTER_NAME AS HEADER FROM APP_CUST a JOIN app b ON a.APP_ID = b.APP_ID JOIN APP_CUST_PERSONAL c ON a.APP_CUST_ID = c.APP_CUST_ID JOIN APP_CUST_ADDR d ON a.APP_CUST_ID = d.APP_CUST_ID JOIN APP_CUST_ATTR_CONTENT e ON e.APP_CUST_ID = a.APP_CUST_ID JOIN REF_MASTER_LOS f ON a.MR_ID_TYPE_CODE = f.REF_MASTER_CODE JOIN REF_MASTER_LOS g ON a.MR_CUST_MODEL_CODE = g.REF_MASTER_CODE JOIN REF_MASTER_LOS h ON d.MR_HOUSE_OWNERSHIP_CODE = h.REF_MASTER_CODE, (SELECT ATTR_VALUE, a.APP_ID FROM APP_CUST_ATTR_CONTENT g JOIN APP_CUST a ON g.APP_CUST_ID = a.APP_CUST_ID JOIN app b ON a.APP_ID = b.APP_ID WHERE APP_NO = '"+ appno +"' AND IS_GUARANTOR = 1 AND g.REF_ATTR_CODE = 'AUTH_AML') as SUBQ WHERE APP_NO = '" + appno +"' AND IS_GUARANTOR = 1 AND MR_CUST_ADDR_TYPE_CODE = 'LEGAL' AND MR_CUST_TYPE_CODE = 'PERSONAL' AND e.REF_ATTR_CODE = 'AML_CUST_DEPARTMENT' AND f.REF_MASTER_TYPE_CODE = 'ID_TYPE' AND g.REF_MASTER_TYPE_CODE = 'CUST_MODEL' AND h.REF_MASTER_TYPE_CODE = 'BUILDING_OWNERSHIP'"), {  row ->

			guarantordata = (row)
		})
		return guarantordata
	}

	@Keyword
	public GuarantorStoreDataCompany (Sql instance, String appno){
		String guarantordata
		instance.eachRow(("SELECT e.REF_MASTER_NAME AS HEADER ,CUST_NAME AS HEADER ,TAX_ID_NO AS HEADER ,MR_COMPANY_TYPE_CODE AS HEADER ,MR_CUST_MODEL_CODE AS HEADER, ADDR AS HEADER, AREA_CODE_4 AS HEADER, AREA_CODE_3 AS HEADER, ZIPCODE AS HEADER, AREA_CODE_2 AS HEADER, AREA_CODE_1 AS HEADER, CITY AS HEADER, f.REF_MASTER_NAME AS HEADER FROM APP_CUST a JOIN app b ON a.APP_ID = b.APP_ID JOIN APP_CUST_COMPANY c ON a.APP_CUST_ID = c.APP_CUST_ID JOIN APP_CUST_ADDR d ON a.APP_CUST_ID = d.APP_CUST_ID JOIN REF_MASTER_LOS e ON e.REF_MASTER_CODE = a.MR_CUST_RELATIONSHIP_CODE JOIN REF_MASTER_LOS f ON f.REF_MASTER_CODE = d.MR_HOUSE_OWNERSHIP_CODE where APP_NO = '"+ appno +"' AND IS_GUARANTOR = 1 AND MR_CUST_ADDR_TYPE_CODE = 'LEGAL' AND MR_CUST_TYPE_CODE = 'COMPANY' AND e.REF_MASTER_TYPE_CODE = 'GUAR_COMPANY_RELATIONSHIP' AND f.REF_MASTER_TYPE_CODE = 'BUILDING_OWNERSHIP'"), {  row ->

			guarantordata = (row)
		})
		return guarantordata
	}
	
	@Keyword
	public CustomerStoreDataCompany (Sql instance, String appno){
		String customerdata
		instance.eachRow(("SELECT CUST_NAME AS HEADER ,TAX_ID_NO AS HEADER ,MR_COMPANY_TYPE_CODE AS HEADER ,MR_CUST_MODEL_CODE AS HEADER, ADDR AS HEADER, AREA_CODE_4 AS HEADER, AREA_CODE_3 AS HEADER, ZIPCODE AS HEADER, AREA_CODE_2 AS HEADER, AREA_CODE_1 AS HEADER, CITY AS HEADER, f.REF_MASTER_NAME AS HEADER FROM APP_CUST a JOIN app b ON a.APP_ID = b.APP_ID JOIN APP_CUST_COMPANY c ON a.APP_CUST_ID = c.APP_CUST_ID JOIN APP_CUST_ADDR d ON a.APP_CUST_ID = d.APP_CUST_ID JOIN REF_MASTER_LOS f ON f.REF_MASTER_CODE = d.MR_HOUSE_OWNERSHIP_CODE where APP_NO = '"+ appno +"' AND IS_CUSTOMER = 1 AND MR_CUST_ADDR_TYPE_CODE = 'LEGAL' AND MR_CUST_TYPE_CODE = 'COMPANY' AND f.REF_MASTER_TYPE_CODE = 'BUILDING_OWNERSHIP'"), {  row ->

			customerdata = (row)
		})
		return customerdata
	}
	
	@Keyword
	public MSStoreDataCompany (Sql instance, String appno){
		String MSdata
		instance.eachRow(("SELECT CUST_NAME AS HEADER, TAX_ID_NO AS HEADER, MR_POSITION_SLIK_CODE AS HEADER, MR_COMPANY_TYPE_CODE AS HEADER, MR_CUST_MODEL_CODE AS HEADER,  FORMAT(SHARE_PRCNT, 'N0') AS HEADER, IS_ACTIVE AS HEADER, IS_OWNER AS HEADER, ADDR AS HEADER, AREA_CODE_3 AS HEADER, AREA_CODE_4 AS HEADER, ZIPCODE AS HEADER, AREA_CODE_1 AS HEADER, AREA_CODE_2 AS HEADER, CITY AS HEADER, MR_HOUSE_OWNERSHIP_CODE AS HEADER FROM APP_CUST a JOIN app b ON a.APP_ID = b.APP_ID JOIN APP_CUST_COMPANY c ON a.APP_CUST_ID = c.APP_CUST_ID JOIN APP_CUST_ADDR d ON a.APP_CUST_ID = d.APP_CUST_ID JOIN APP_CUST_COMPANY_MGMNT_SHRHOLDER e ON a.APP_CUST_ID = e.APP_CUST_ID where APP_NO = '"+ appno +"' AND IS_SHAREHOLDER = 1 AND MR_CUST_ADDR_TYPE_CODE = 'LEGAL' AND MR_CUST_TYPE_CODE = 'COMPANY'"), {  row ->

			MSdata = (row)
		})
		return MSdata
	}
	
	@Keyword
	public MSStoreDataPersonal (Sql instance, String appno){
		String MSdata
		instance.eachRow(("SELECT Cust_name AS HEADER , BIRTH_PLACE AS HEADER, j.REF_MASTER_NAME AS HEADER, FORMAT(ID_EXPIRED_DT, 'MM/dd/yyyy') AS HEADER, MR_MARITAL_STAT_CODE AS HEADER, MOBILE_PHN_NO_1 AS HEADER, h.REF_MASTER_NAME AS HEADER, f.MR_PROFESSION_CODE AS HEADER, MR_POSITION_SLIK_CODE AS HEADER, FORMAT(e.ESTABLISHMENT_DT, 'MM/dd/yyyy') AS HEADER, MR_GENDER_CODE AS HEADER, FORMAT(BIRTH_DT, 'MM/dd/yyyy') AS HEADER, ID_NO AS HEADER, TAX_ID_NO AS HEADER, MOTHER_MAIDEN_NAME AS HEADER, EMAIL_1 AS HEADER, e.MR_JOB_POSITION_CODE AS HEADER, FORMAT(SHARE_PRCNT, 'N0') AS HEADER, IS_OWNER AS HEADER, e.IS_ACTIVE AS HEADER, IS_SIGNER AS HEADER, g.ATTR_VALUE AS HEADER, SUBQ.ATTR_VALUE AS HEADER, ADDR AS HEADER, AREA_CODE_4 AS HEADER, AREA_CODE_3 AS HEADER, ZIPCODE AS HEADER, AREA_CODE_2 AS HEADER, AREA_CODE_1 AS HEADER, CITY AS HEADER, i.REF_MASTER_NAME AS HEADER FROM APP_CUST a JOIN app b ON a.APP_ID = b.APP_ID JOIN APP_CUST_PERSONAL c ON a.APP_CUST_ID = c.APP_CUST_ID JOIN APP_CUST_ADDR d ON a.APP_CUST_ID = d.APP_CUST_ID JOIN APP_CUST_COMPANY_MGMNT_SHRHOLDER e ON c.APP_CUST_ID = e.APP_CUST_ID JOIN APP_CUST_PERSONAL_JOB_DATA f ON f.APP_CUST_PERSONAL_ID = c.APP_CUST_PERSONAL_ID JOIN APP_CUST_ATTR_CONTENT g ON g.APP_CUST_ID = a.APP_CUST_ID JOIN REF_MASTER_LOS h ON h.REF_MASTER_CODE = a.MR_CUST_MODEL_CODE JOIN REF_MASTER_LOS i ON d.MR_HOUSE_OWNERSHIP_CODE = i.REF_MASTER_CODE JOIN REF_MASTER_LOS j ON a.MR_ID_TYPE_CODE = j.REF_MASTER_CODE, (SELECT ATTR_VALUE, a.APP_ID FROM APP_CUST_ATTR_CONTENT g JOIN APP_CUST a ON g.APP_CUST_ID = a.APP_CUST_ID JOIN app b ON a.APP_ID = b.APP_ID WHERE APP_NO = '"+ appno +"' AND IS_SHAREHOLDER = 1 AND g.REF_ATTR_CODE = 'AUTH_AML') as SUBQ where a.APP_ID = SUBQ.APP_ID AND MR_CUST_ADDR_TYPE_CODE = 'LEGAL' AND e.MR_SHRHOLDER_TYPE_CODE = 'PERSONAL' AND g.REF_ATTR_CODE = 'AML_CUST_DEPARTMENT' AND h.REF_MASTER_TYPE_CODE = 'CUST_MODEL' AND i.REF_MASTER_TYPE_CODE = 'BUILDING_OWNERSHIP' AND j.REF_MASTER_TYPE_CODE = 'ID_TYPE'"), {  row ->

			MSdata = (row)
		})
		return MSdata
	}
}
