package dbconnection

import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import static com.kms.katalon.core.testobject.ObjectRepository.findWindowsObject

import com.kms.katalon.core.annotation.Keyword
import com.kms.katalon.core.checkpoint.Checkpoint
import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling
import com.kms.katalon.core.testcase.TestCase
import com.kms.katalon.core.testdata.TestData
import com.kms.katalon.core.testobject.TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import com.kms.katalon.core.windows.keyword.WindowsBuiltinKeywords as Windows

import groovy.sql.Sql
import internal.GlobalVariable

public class CustomerDataVerif {

	@Keyword
	public CustomerDataPersonal (Sql instance, String name, String idtype, String custmodel){
		String customerdata
		instance.eachRow(("select DISTINCT Cust_name AS HEADER, BIRTH_PLACE AS HEADER, MR_ID_TYPE_CODE AS HEADER, ID_EXPIRED_DT AS HEADER, MR_MARITAL_STAT_CODE AS HEADER, MOBILE_PHN_NO_1 AS HEADER, MR_CUST_MODEL_CODE AS HEADER, MR_GENDER_CODE AS HEADER, FORMAT(BIRTH_DT, 'yyyy-MM-dd') AS HEADER, ID_NO AS HEADER, TAX_ID_NO AS HEADER, MOTHER_MAIDEN_NAME AS HEADER, EMAIL_1 AS HEADER, ADDR AS HEADER, AREA_CODE_4 AS HEADER, AREA_CODE_3 AS HEADER, ZIPCODE AS HEADER, AREA_CODE_2 AS HEADER, AREA_CODE_1 AS HEADER, CITY AS HEADER, MR_BUILDING_OWNERSHIP_CODE AS HEADER from cust a join cust_addr b on a.CUST_ID = b.CUST_ID JOIN cust_personal c on a.cust_ID = c.CUST_ID where a.cust_name = '"+ name +"' and MR_ID_TYPE_CODE = '"+ idtype +"' AND MR_CUST_MODEL_CODE = '"+ custmodel + "' AND MR_CUST_ADDR_TYPE_CODE = 'legal'"), {  row ->

			customerdata = (row)
		})
		return customerdata
	}

	@Keyword
	public CustomerDataCompany (Sql instance, String name, String companytype){
		String customerdata
		instance.eachRow(("select DISTINCT Cust_name AS HEADER, TAX_ID_NO AS HEADER, MR_COMPANY_TYPE_CODE AS HEADER ,MR_CUST_MODEL_CODE AS HEADER, ADDR AS HEADER, AREA_CODE_4 AS HEADER, AREA_CODE_3 AS HEADER, ZIPCODE AS HEADER, AREA_CODE_2 AS HEADER, AREA_CODE_1 AS HEADER, CITY AS HEADER, MR_BUILDING_OWNERSHIP_CODE AS HEADER from cust a join cust_addr b on a.CUST_ID = b.CUST_ID JOIN CUST_COMPANY c on a.cust_ID = c.CUST_ID where a.cust_name = '"+ name +"' AND MR_COMPANY_TYPE_CODE = '"+ companytype +"' AND MR_CUST_ADDR_TYPE_CODE = 'legal'"), {  row ->

			customerdata = (row)
		})
		return customerdata
	}

	@Keyword
	public FamilyDataPersonal (Sql instance, String name, String idno){
		String customerdata
		instance.eachRow(("select Cust_name AS HEADER, BIRTH_PLACE AS HEADER, MR_ID_TYPE_CODE AS HEADER, ID_EXPIRED_DT AS HEADER, MR_MARITAL_STAT_CODE AS HEADER, MOBILE_PHN_NO_1 AS HEADER, MR_CUST_MODEL_CODE AS HEADER, MR_GENDER_CODE AS HEADER, FORMAT(BIRTH_DT, 'yyyy-MM-dd') AS HEADER, ID_NO AS HEADER, TAX_ID_NO AS HEADER, MOTHER_MAIDEN_NAME AS HEADER, EMAIL_1 AS HEADER, MR_NATIONALITY_CODE AS HEADER, UPPER(COUNTRY_NAME) AS HEADER, ADDR AS HEADER, AREA_CODE_4 AS HEADER, AREA_CODE_3 AS HEADER, ZIPCODE AS HEADER, AREA_CODE_2 AS HEADER, AREA_CODE_1 AS HEADER, CITY AS HEADER, MR_BUILDING_OWNERSHIP_CODE AS HEADER from cust a join cust_addr b on a.CUST_ID = b.CUST_ID join cust_personal c on a.cust_ID = c.CUST_ID join REF_COUNTRY d on c.WNA_COUNTRY_CODE = d.COUNTRY_CODE where a.cust_name = '"+ name + "' AND ID_NO = '"+ idno +"' AND MR_CUST_ADDR_TYPE_CODE = 'legal'"), {  row ->

			customerdata = (row)
		})
		return customerdata
	}

	@Keyword
	public CheckCustomerExisting (Sql instance, String appno){
		int checkresult
		instance.eachRow(("USE LOS SELECT COUNT(IS_EXISTING_CUST) FROM APP_CUST a JOIN APP b on a.APP_ID = b.APP_ID WHERE APP_NO = '"+ appno + "' and IS_CUSTOMER = 1"), {  row ->

			checkresult = (row[0])
		})
		return checkresult
	}

	@Keyword
	public CustomerDataStoreDBPersonal (Sql instance, String appno){
		String customerdata
		instance.eachRow(("SELECT b.PROD_OFFERING_CODE AS HEADER, Cust_name AS HEADER, BIRTH_PLACE AS HEADER, h.REF_MASTER_NAME AS HEADER, FORMAT(ID_EXPIRED_DT, 'MM/dd/yyyy') AS HEADER, MR_MARITAL_STAT_CODE AS HEADER, MOBILE_PHN_NO_1 AS HEADER, f.REF_MASTER_NAME AS HEADER, MR_GENDER_CODE AS HEADER, FORMAT(BIRTH_DT, 'MM/dd/yyyy') AS HEADER, ID_NO AS HEADER, TAX_ID_NO AS HEADER, MOTHER_MAIDEN_NAME AS HEADER, EMAIL_1 AS HEADER, e.ATTR_VALUE AS HEADER, SUBQ.ATTR_VALUE AS HEADER, ADDR AS HEADER, AREA_CODE_4 AS HEADER, AREA_CODE_3 AS HEADER, ZIPCODE AS HEADER, AREA_CODE_2 AS HEADER, AREA_CODE_1 AS HEADER, CITY AS HEADER, g.REF_MASTER_NAME AS HEADER FROM APP_CUST a JOIN app b ON a.APP_ID = b.APP_ID JOIN APP_CUST_PERSONAL c ON a.APP_CUST_ID = c.APP_CUST_ID JOIN APP_CUST_ADDR d ON a.APP_CUST_ID = d.APP_CUST_ID JOIN APP_CUST_ATTR_CONTENT e ON e.APP_CUST_ID = a.APP_CUST_ID JOIN REF_MASTER_LOS f ON a.MR_CUST_MODEL_CODE = f.REF_MASTER_CODE JOIN REF_MASTER_LOS g ON d.MR_HOUSE_OWNERSHIP_CODE = g.REF_MASTER_CODE JOIN REF_MASTER_LOS h ON a.MR_ID_TYPE_CODE = h.REF_MASTER_CODE, (SELECT ATTR_VALUE, a.APP_ID FROM APP_CUST_ATTR_CONTENT g JOIN APP_CUST a ON g.APP_CUST_ID = a.APP_CUST_ID JOIN app b ON a.APP_ID = b.APP_ID WHERE APP_NO = '"+ appno +"'AND IS_CUSTOMER = 1 AND g.REF_ATTR_CODE = 'AUTH_AML') as SUBQ WHERE a.APP_ID = SUBQ.APP_ID AND IS_CUSTOMER = 1 AND MR_CUST_ADDR_TYPE_CODE = 'LEGAL' AND MR_CUST_TYPE_CODE = 'PERSONAL' AND e.REF_ATTR_CODE = 'AML_CUST_DEPARTMENT' AND f.REF_MASTER_TYPE_CODE = 'CUST_MODEL' AND g.REF_MASTER_TYPE_CODE = 'BUILDING_OWNERSHIP' AND h.REF_MASTER_TYPE_CODE = 'ID_TYPE'"), {  row ->

			customerdata = (row)
		})
		return customerdata
	}

	@Keyword
	public FamilyDataStoreDBPersonal (Sql instance, String appno){
		String familydata
		instance.eachRow(("SELECT MR_CUST_RELATIONSHIP_CODE AS HEADER ,Cust_name AS HEADER, BIRTH_PLACE AS HEADER, g.REF_MASTER_NAME AS HEADER, FORMAT(ID_EXPIRED_DT, 'MM/dd/yyyy') AS HEADER, MR_MARITAL_STAT_CODE AS HEADER, MOBILE_PHN_NO_1 AS HEADER, h.REF_MASTER_NAME AS HEADER, e.MR_PROFESSION_CODE AS HEADER, FORMAT(e.ESTABLISHMENT_DT, 'MM/dd/yyyy') AS HEADER, MR_GENDER_CODE AS HEADER, FORMAT(BIRTH_DT, 'MM/dd/yyyy') AS HEADER, ID_NO AS HEADER, TAX_ID_NO AS HEADER, MOTHER_MAIDEN_NAME AS HEADER, EMAIL_1 AS HEADER, MR_NATIONALITY_CODE AS HEADER, NATIONALITY_COUNTRY_CODE AS HEADER, MR_JOB_POSITION_CODE AS HEADER, f.ATTR_VALUE AS HEADER, SUBQ.ATTR_VALUE AS HEADER, ADDR AS HEADER, AREA_CODE_4 AS HEADER, AREA_CODE_3 AS HEADER, ZIPCODE AS HEADER, AREA_CODE_2 AS HEADER, AREA_CODE_1 AS HEADER, CITY AS HEADER, i.REF_MASTER_NAME AS HEADER FROM APP_CUST a JOIN app b ON a.APP_ID = b.APP_ID JOIN APP_CUST_PERSONAL c ON a.APP_CUST_ID = c.APP_CUST_ID JOIN APP_CUST_ADDR d ON a.APP_CUST_ID = d.APP_CUST_ID JOIN APP_CUST_PERSONAL_JOB_DATA e ON c.APP_CUST_PERSONAL_ID = e.APP_CUST_PERSONAL_ID JOIN APP_CUST_ATTR_CONTENT f ON f.APP_CUST_ID = a.APP_CUST_ID JOIN REF_MASTER_LOS g ON a.MR_ID_TYPE_CODE = g.REF_MASTER_CODE JOIN REF_MASTER_LOS h ON a.MR_CUST_MODEL_CODE = h.REF_MASTER_CODE JOIN REF_MASTER_LOS i ON d.MR_HOUSE_OWNERSHIP_CODE = i.REF_MASTER_CODE, (SELECT ATTR_VALUE, a.APP_ID FROM APP_CUST_ATTR_CONTENT g JOIN APP_CUST a ON g.APP_CUST_ID = a.APP_CUST_ID JOIN app b ON a.APP_ID = b.APP_ID WHERE APP_NO = '"+ appno +"' AND IS_FAMILY = 1 AND g.REF_ATTR_CODE = 'AUTH_AML') as SUBQ where a.APP_ID = SUBQ.APP_ID AND IS_FAMILY = 1 AND MR_CUST_ADDR_TYPE_CODE = 'LEGAL' AND MR_CUST_TYPE_CODE = 'PERSONAL' AND f.REF_ATTR_CODE = 'AML_CUST_DEPARTMENT' AND g.REF_MASTER_TYPE_CODE = 'ID_TYPE' AND h.REF_MASTER_TYPE_CODE = 'CUST_MODEL' AND i.REF_MASTER_TYPE_CODE = 'BUILDING_OWNERSHIP'"), {  row ->

			familydata = (row)
		})
		return familydata
	}

	@Keyword
	public GuarantorDataStoreDBPersonal (Sql instance, String appno){
		String guarantordata
		instance.eachRow(("SELECT MR_CUST_RELATIONSHIP_CODE AS HEADER ,Cust_name AS HEADER, BIRTH_PLACE AS HEADER, f.REF_MASTER_NAME AS HEADER, FORMAT(ID_EXPIRED_DT, 'MM/dd/yyyy') AS HEADER, MR_MARITAL_STAT_CODE AS HEADER, MOBILE_PHN_NO_1 AS HEADER, g.REF_MASTER_NAME AS HEADER, MR_GENDER_CODE AS HEADER, FORMAT(BIRTH_DT, 'MM/dd/yyyy') AS HEADER, ID_NO AS HEADER, TAX_ID_NO AS HEADER, MOTHER_MAIDEN_NAME AS HEADER, EMAIL_1 AS HEADER, e.ATTR_VALUE AS HEADER, SUBQ.ATTR_VALUE AS HEADER, ADDR AS HEADER, AREA_CODE_4 AS HEADER, AREA_CODE_3 AS HEADER, ZIPCODE AS HEADER, AREA_CODE_2 AS HEADER, AREA_CODE_1 AS HEADER, CITY AS HEADER, h.REF_MASTER_NAME AS HEADER FROM APP_CUST a JOIN app b ON a.APP_ID = b.APP_ID JOIN APP_CUST_PERSONAL c ON a.APP_CUST_ID = c.APP_CUST_ID JOIN APP_CUST_ADDR d ON a.APP_CUST_ID = d.APP_CUST_ID JOIN APP_CUST_ATTR_CONTENT e ON e.APP_CUST_ID = a.APP_CUST_ID JOIN REF_MASTER_LOS f ON a.MR_ID_TYPE_CODE = f.REF_MASTER_CODE JOIN REF_MASTER_LOS g ON a.MR_CUST_MODEL_CODE = g.REF_MASTER_CODE JOIN REF_MASTER_LOS h ON d.MR_HOUSE_OWNERSHIP_CODE = h.REF_MASTER_CODE, (SELECT ATTR_VALUE, a.APP_ID FROM APP_CUST_ATTR_CONTENT g JOIN APP_CUST a ON g.APP_CUST_ID = a.APP_CUST_ID JOIN app b ON a.APP_ID = b.APP_ID WHERE APP_NO = '"+ appno +"' AND IS_GUARANTOR = 1 AND g.REF_ATTR_CODE = 'AUTH_AML') as SUBQ WHERE APP_NO = '" + appno +"' AND IS_GUARANTOR = 1 AND MR_CUST_ADDR_TYPE_CODE = 'LEGAL' AND MR_CUST_TYPE_CODE = 'PERSONAL' AND e.REF_ATTR_CODE = 'AML_CUST_DEPARTMENT' AND f.REF_MASTER_TYPE_CODE = 'ID_TYPE' AND g.REF_MASTER_TYPE_CODE = 'CUST_MODEL' AND h.REF_MASTER_TYPE_CODE = 'BUILDING_OWNERSHIP'"), {  row ->

			guarantordata = (row)
		})
		return guarantordata
	}

	@Keyword
	public GuarantorDataStoreDBCompany (Sql instance, String appno){
		String guarantordata
		instance.eachRow(("SELECT e.REF_MASTER_NAME AS HEADER ,CUST_NAME AS HEADER ,TAX_ID_NO AS HEADER ,MR_COMPANY_TYPE_CODE AS HEADER ,MR_CUST_MODEL_CODE AS HEADER, ADDR AS HEADER, AREA_CODE_4 AS HEADER, AREA_CODE_3 AS HEADER, ZIPCODE AS HEADER, AREA_CODE_2 AS HEADER, AREA_CODE_1 AS HEADER, CITY AS HEADER, f.REF_MASTER_NAME AS HEADER FROM APP_CUST a JOIN app b ON a.APP_ID = b.APP_ID JOIN APP_CUST_COMPANY c ON a.APP_CUST_ID = c.APP_CUST_ID JOIN APP_CUST_ADDR d ON a.APP_CUST_ID = d.APP_CUST_ID JOIN REF_MASTER_LOS e ON e.REF_MASTER_CODE = a.MR_CUST_RELATIONSHIP_CODE JOIN REF_MASTER_LOS f ON f.REF_MASTER_CODE = d.MR_HOUSE_OWNERSHIP_CODE where APP_NO = '"+ appno +"' AND IS_GUARANTOR = 1 AND MR_CUST_ADDR_TYPE_CODE = 'LEGAL' AND MR_CUST_TYPE_CODE = 'COMPANY' AND e.REF_MASTER_TYPE_CODE = 'GUAR_COMPANY_RELATIONSHIP' AND f.REF_MASTER_TYPE_CODE = 'BUILDING_OWNERSHIP'"), {  row ->

			guarantordata = (row)
		})
		return guarantordata
	}

	@Keyword
	public CustomerDataStoreDBCompany (Sql instance, String appno){
		String customerdata
		instance.eachRow(("SELECT CUST_NAME AS HEADER ,TAX_ID_NO AS HEADER ,MR_COMPANY_TYPE_CODE AS HEADER ,MR_CUST_MODEL_CODE AS HEADER, ADDR AS HEADER, AREA_CODE_4 AS HEADER, AREA_CODE_3 AS HEADER, ZIPCODE AS HEADER, AREA_CODE_2 AS HEADER, AREA_CODE_1 AS HEADER, CITY AS HEADER, f.REF_MASTER_NAME AS HEADER FROM APP_CUST a JOIN app b ON a.APP_ID = b.APP_ID JOIN APP_CUST_COMPANY c ON a.APP_CUST_ID = c.APP_CUST_ID JOIN APP_CUST_ADDR d ON a.APP_CUST_ID = d.APP_CUST_ID JOIN REF_MASTER_LOS f ON f.REF_MASTER_CODE = d.MR_HOUSE_OWNERSHIP_CODE where APP_NO = '"+ appno +"' AND IS_CUSTOMER = 1 AND MR_CUST_ADDR_TYPE_CODE = 'LEGAL' AND MR_CUST_TYPE_CODE = 'COMPANY' AND f.REF_MASTER_TYPE_CODE = 'BUILDING_OWNERSHIP'"), {  row ->

			customerdata = (row)
		})
		return customerdata
	}

	@Keyword
	public MSDataStoreDBCompany (Sql instance, String appno){
		String MSdata
		instance.eachRow(("SELECT CUST_NAME AS HEADER, TAX_ID_NO AS HEADER, MR_POSITION_SLIK_CODE AS HEADER, MR_COMPANY_TYPE_CODE AS HEADER, MR_CUST_MODEL_CODE AS HEADER,  FORMAT(SHARE_PRCNT, 'N0') AS HEADER, IS_ACTIVE AS HEADER, IS_OWNER AS HEADER, ADDR AS HEADER, AREA_CODE_3 AS HEADER, AREA_CODE_4 AS HEADER, ZIPCODE AS HEADER, AREA_CODE_1 AS HEADER, AREA_CODE_2 AS HEADER, CITY AS HEADER, MR_HOUSE_OWNERSHIP_CODE AS HEADER FROM APP_CUST a JOIN app b ON a.APP_ID = b.APP_ID JOIN APP_CUST_COMPANY c ON a.APP_CUST_ID = c.APP_CUST_ID JOIN APP_CUST_ADDR d ON a.APP_CUST_ID = d.APP_CUST_ID JOIN APP_CUST_COMPANY_MGMNT_SHRHOLDER e ON a.APP_CUST_ID = e.APP_CUST_ID where APP_NO = '"+ appno +"' AND IS_SHAREHOLDER = 1 AND MR_CUST_ADDR_TYPE_CODE = 'LEGAL' AND MR_CUST_TYPE_CODE = 'COMPANY'"), {  row ->

			MSdata = (row)
		})
		return MSdata
	}

	@Keyword
	public MSDataStoreDBPersonal (Sql instance, String appno){
		String MSdata
		instance.eachRow(("SELECT Cust_name AS HEADER , BIRTH_PLACE AS HEADER, j.REF_MASTER_NAME AS HEADER, FORMAT(ID_EXPIRED_DT, 'MM/dd/yyyy') AS HEADER, MR_MARITAL_STAT_CODE AS HEADER, MOBILE_PHN_NO_1 AS HEADER, h.REF_MASTER_NAME AS HEADER, f.MR_PROFESSION_CODE AS HEADER, MR_POSITION_SLIK_CODE AS HEADER, FORMAT(e.ESTABLISHMENT_DT, 'MM/dd/yyyy') AS HEADER, MR_GENDER_CODE AS HEADER, FORMAT(BIRTH_DT, 'MM/dd/yyyy') AS HEADER, ID_NO AS HEADER, TAX_ID_NO AS HEADER, MOTHER_MAIDEN_NAME AS HEADER, EMAIL_1 AS HEADER, e.MR_JOB_POSITION_CODE AS HEADER, FORMAT(SHARE_PRCNT, 'N0') AS HEADER, IS_OWNER AS HEADER, e.IS_ACTIVE AS HEADER, IS_SIGNER AS HEADER, g.ATTR_VALUE AS HEADER, SUBQ.ATTR_VALUE AS HEADER, ADDR AS HEADER, AREA_CODE_4 AS HEADER, AREA_CODE_3 AS HEADER, ZIPCODE AS HEADER, AREA_CODE_2 AS HEADER, AREA_CODE_1 AS HEADER, CITY AS HEADER, i.REF_MASTER_NAME AS HEADER FROM APP_CUST a JOIN app b ON a.APP_ID = b.APP_ID JOIN APP_CUST_PERSONAL c ON a.APP_CUST_ID = c.APP_CUST_ID JOIN APP_CUST_ADDR d ON a.APP_CUST_ID = d.APP_CUST_ID JOIN APP_CUST_COMPANY_MGMNT_SHRHOLDER e ON c.APP_CUST_ID = e.APP_CUST_ID JOIN APP_CUST_PERSONAL_JOB_DATA f ON f.APP_CUST_PERSONAL_ID = c.APP_CUST_PERSONAL_ID JOIN APP_CUST_ATTR_CONTENT g ON g.APP_CUST_ID = a.APP_CUST_ID JOIN REF_MASTER_LOS h ON h.REF_MASTER_CODE = a.MR_CUST_MODEL_CODE JOIN REF_MASTER_LOS i ON d.MR_HOUSE_OWNERSHIP_CODE = i.REF_MASTER_CODE JOIN REF_MASTER_LOS j ON a.MR_ID_TYPE_CODE = j.REF_MASTER_CODE, (SELECT ATTR_VALUE, a.APP_ID FROM APP_CUST_ATTR_CONTENT g JOIN APP_CUST a ON g.APP_CUST_ID = a.APP_CUST_ID JOIN app b ON a.APP_ID = b.APP_ID WHERE APP_NO = '"+ appno +"' AND IS_SHAREHOLDER = 1 AND g.REF_ATTR_CODE = 'AUTH_AML') as SUBQ where a.APP_ID = SUBQ.APP_ID AND MR_CUST_ADDR_TYPE_CODE = 'LEGAL' AND e.MR_SHRHOLDER_TYPE_CODE = 'PERSONAL' AND g.REF_ATTR_CODE = 'AML_CUST_DEPARTMENT' AND h.REF_MASTER_TYPE_CODE = 'CUST_MODEL' AND i.REF_MASTER_TYPE_CODE = 'BUILDING_OWNERSHIP' AND j.REF_MASTER_TYPE_CODE = 'ID_TYPE'"), {  row ->

			MSdata = (row)
		})
		return MSdata
	}

	@Keyword
	public NAP2TabReferantorStoreDB (Sql instance, String appno){
		String referantordata
		ArrayList <String> listreferantor = new ArrayList<String>()
		instance.eachRow(("SELECT DISTINCT CASE WHEN MR_REFERANTOR_TYPE = 'AGENCY_PERSONAL' OR MR_REFERANTOR_TYPE = 'AGENCY_COMPANY' THEN 'AGENCY' WHEN MR_REFERANTOR_TYPE = 'CUSTOMER_PERSONAL' OR MR_REFERANTOR_TYPE = 'CUSTOMER_COMPANY' THEN 'CUSTOMER' ELSE 'MULTIFINANCE EMPLOYEE' END, c.REFERANTOR_NAME, c.BANK_ACC_NAME, c.MR_TAX_CALC_METHOD FROM APP_CUST a JOIN APP b ON a.APP_ID = b.APP_ID JOIN APP_REFERANTOR c ON a.APP_ID = c.APP_ID WHERE APP_NO = '"+ appno +"'"), {  row ->

			referantordata = (row[0])
			listreferantor.add(referantordata)
			referantordata = (row[1])
			listreferantor.add(referantordata)
			referantordata = (row[2])
			listreferantor.add(referantordata)
			referantordata = (row[3])
			listreferantor.add(referantordata)
		})
		return listreferantor
	}


	@Keyword
	public NAP2TabApplicationStoreDB (Sql instance, String appno){
		String applicationdata
		instance.eachRow(("SELECT DISTINCT d.APP_SRC_NAME AS HEADER, e.REF_MASTER_NAME AS HEADER, PAY_FREQ_CODE AS HEADER, TENOR AS HEADER, p.REF_MASTER_NAME AS HEADER, t.REF_MASTER_NAME AS HEADER, FLOATING_PERIOD_CODE AS HEADER, r.REF_MASTER_NAME AS HEADER, f.REF_MASTER_NAME AS HEADER, 'asd' AS HEADER, g.REF_MASTER_NAME AS HEADER, s.REF_MASTER_NAME AS HEADER, c.ADDR AS HEADER, c.AREA_CODE_3 AS HEADER, c.AREA_CODE_4 AS HEADER, c.ZIPCODE AS HEADER, c.AREA_CODE_1 AS HEADER, c.AREA_CODE_2 AS HEADER, c.CITY AS HEADER, c.PHN_AREA_1 AS HEADER, c.PHN_1 AS HEADER, c.PHN_EXT_1 AS HEADER, c.PHN_AREA_2 AS HEADER, c.PHN_2 AS HEADER, c.PHN_EXT_2 AS HEADER , c.PHN_AREA_3 AS HEADER, c.PHN_3 AS HEADER, c.PHN_EXT_3 AS HEADER, c.FAX_AREA AS HEADER, c.FAX AS HEADER, m.REF_MASTER_NAME AS HEADER, l.PREV_AGRMNT_NO AS HEADER, n.REF_MASTER_NAME AS HEADER, l.MR_SLIK_SEC_ECO_CODE AS HEADER, h.ATTR_VALUE AS HEADER, i.ATTR_VALUE AS HEADER, j.ATTR_VALUE AS HEADER, k.ATTR_VALUE AS HEADER, jk.ATTR_VALUE AS HEADER FROM APP a JOIN APP_CUST b ON a.APP_ID = b.APP_ID JOIN APP_CUST_ADDR c ON b.APP_CUST_ID = c.APP_CUST_ID JOIN REF_APP_SRC d ON d.APP_SRC_CODE = a.MR_APP_SOURCE_CODE JOIN REF_MASTER_LOS e ON e.REF_MASTER_CODE = a.MR_FIRST_INST_TYPE_CODE JOIN REF_MASTER_LOS f ON f.REF_MASTER_CODE = a.MR_WOP_CODE JOIN REF_MASTER_LOS g ON g.REF_MASTER_CODE = a.MR_CUST_NOTIFY_OPT_CODE JOIN APP_ATTR_CONTENT h ON h.APP_ID = a.APP_ID JOIN APP_ATTR_CONTENT i ON i.APP_ID = a.APP_ID JOIN APP_ATTR_CONTENT j ON j.APP_ID = a.APP_ID JOIN APP_ATTR_CONTENT k ON k.APP_ID = a.APP_ID JOIN APP_ATTR_CONTENT jk ON jk.APP_ID = a.APP_ID JOIN APP_GOVERMENT_REGULATION l ON l.APP_ID = a.APP_ID JOIN REF_MASTER_LOS m ON m.REF_MASTER_CODE = l.MR_CHARACTERISTIC_OF_CREDIT_CODE JOIN REF_MASTER_LOS n ON n.REF_MASTER_CODE = l.MR_WAY_OF_RESTRUCTURE_CODE JOIN REF_MASTER_LOS o ON o.REF_MASTER_CODE = l.MR_SLIK_SEC_ECO_CODE JOIN REF_MASTER_LOS p ON p.REF_MASTER_CODE = l.MR_DP_SRC_PAYMENT_CODE JOIN APP_FIN_DATA q ON q.APP_ID = b.APP_ID JOIN REF_MASTER_LOS r ON r.REF_MASTER_CODE = q.MR_INST_SCHEME_CODE JOIN REF_MASTER_LOS s ON s.REF_MASTER_CODE = l.MR_INST_SRC_PAYMENT_CODE JOIN REF_MASTER_LOS t ON t.REF_MASTER_CODE = q.INTEREST_TYPE WHERE APP_NO = '"+ appno +"' AND c.MR_CUST_ADDR_TYPE_CODE = 'MAILING' AND e.REF_MASTER_TYPE_CODE = 'FIRST_INST_TYPE' AND f.REF_MASTER_TYPE_CODE = 'WOP' AND h.REF_ATTR_CODE = 'BLCKLST_APPI' AND i.REF_ATTR_CODE = 'APPI_SCR' AND j.REF_ATTR_CODE = 'DATE_APP_DATA' AND k.REF_ATTR_CODE = 'REF_MASTER_APP_DATA' AND jk.REF_ATTR_CODE = 'ATTR_NAP_TEST' AND n.REF_MASTER_TYPE_CODE = 'WAY_OF_RESTRUCTURE'"), {  row ->

			applicationdata = (row)
		})
		return applicationdata
	}


	@Keyword
	public NAP2TabAssetStoreDB (Sql instance, String appno){
		String applicationdata
		instance.eachRow(("SELECT SUPPL_CODE AS HEADER, SUPPL_NAME AS HEADER, d.SUPPL_EMP_NAME AS HEADER, e.SUPPL_EMP_NAME AS HEADER, a.FULL_ASSET_CODE AS HEADER, MR_ASSET_CONDITION_CODE AS HEADER, ASSET_PRICE_AMT AS HEADER, h.REF_MASTER_NAME AS HEADER, a.COLOR AS HEADER, a.TAX_CITY_ISSUER AS HEADER, FORMAT(a.ASSET_TAX_DT, 'MM/dd/yyy') AS HEADER, a.ASSET_NOTES AS HEADER, a.MANUFACTURING_YEAR AS HEADER, CONVERT(INT, DOWN_PAYMENT_PRCNT) AS HEADER, CONVERT(INT, DOWN_PAYMENT_AMT) AS HEADER, a.SERIAL_NO_1 AS HEADER, a.SERIAL_NO_2 AS HEADER, a.SERIAL_NO_3 AS HEADER, a.SERIAL_NO_4 AS HEADER, a.SERIAL_NO_5 AS HEADER, c.ATTR_VALUE AS HEADER, g.USER_NAME AS HEADER, i.REF_MASTER_NAME AS HEADER, g.MR_OWNER_TYPE_CODE AS HEADER, g.OWNER_NAME AS HEADER, i.REF_MASTER_NAME AS HEADER, g.OWNER_PROFESSION_CODE AS HEADER, j.REF_MASTER_NAME AS HEADER, g.OWNER_ID_NO AS HEADER, g.OWNER_MOBILE_PHN_NO AS HEADER, g.OWNER_ADDR AS HEADER, g.LOCATION_AREA_CODE_3 AS HEADER, g.LOCATION_AREA_CODE_4 AS HEADER, g.OWNER_ZIPCODE AS HEADER, g.OWNER_AREA_CODE_1 AS HEADER, g.OWNER_AREA_CODE_2 AS HEADER, g.OWNER_CITY AS HEADER, g.LOCATION_ADDR AS HEADER, g.LOCATION_AREA_CODE_3 AS HEADER, g.LOCATION_AREA_CODE_4 AS HEADER, g.LOCATION_ZIPCODE AS HEADER, g.LOCATION_AREA_CODE_1 AS HEADER, g.LOCATION_AREA_CODE_2 AS HEADER, g.LOCATION_CITY AS HEADER FROM APP_ASSET a JOIN APP b ON a.APP_ID = b.APP_ID JOIN APP_ASSET_ATTR c ON a.APP_ASSET_ID = c.APP_ASSET_ID JOIN APP_ASSET_SUPPL_EMP d ON a.APP_ASSET_ID = d.APP_ASSET_ID JOIN APP_ASSET_SUPPL_EMP e ON a.APP_ASSET_ID = e.APP_ASSET_ID JOIN APP_COLLATERAL f ON a.APP_ID = f.APP_ID JOIN APP_COLLATERAL_REGISTRATION g ON f.APP_COLLATERAL_ID = g.APP_COLLATERAL_ID JOIN REF_MASTER_LOS h ON h.REF_MASTER_CODE = a.MR_ASSET_USAGE_CODE JOIN REF_MASTER_LOS i ON i.REF_MASTER_CODE = g.MR_OWNER_RELATIONSHIP_CODE JOIN REF_MASTER_LOS j ON j.REF_MASTER_CODE = g.MR_ID_TYPE_CODE WHERE APP_NO = '"+ appno +"' AND c.ASSET_ATTR_NAME = 'ASSET REGION' AND d.MR_SUPPL_EMP_POSITION_CODE = 'SALES_PERSON' AND e.MR_SUPPL_EMP_POSITION_CODE = 'ADMIN_HEAD' AND h.REF_MASTER_TYPE_CODE = 'ASSET_USAGE' AND i.REF_MASTER_TYPE_CODE = 'CUST_PERSONAL_RELATIONSHIP'AND j.REF_MASTER_TYPE_CODE = 'ID_TYPE'"), {  row ->

			applicationdata = (row)
		})
		return applicationdata
	}

	@Keyword
	public NAP2AccessoriesStoreDB (Sql instance, String appno){
		String accessoriesdata
		ArrayList <String> listaccessories = new ArrayList<String>()
		instance.eachRow(("SELECT b.SUPPL_CODE AS HEADER, b.SUPPL_NAME AS HEADER, a.ASSET_ACCESSORY_CODE AS HEADER, a.ASSET_ACCESSORY_NAME AS HEADER, CONVERT(INT, a.ACCESSORY_PRICE_AMT) AS HEADER, CONVERT(INT, a.DOWN_PAYMENT_PRCNT) AS HEADER, CONVERT(INT, a.DOWN_PAYMENT_AMT) AS HEADER, a.ACCESSORY_NOTES AS HEADER FROM APP_ASSET_ACCESSORY a JOIN APP_ASSET b ON a.APP_ASSET_ID = b.APP_ASSET_ID JOIN APP c ON b.APP_ID = c.APP_ID WHERE APP_NO = '"+ appno +"'"), {  row ->

			accessoriesdata = (row[0])
			listaccessories.add(accessoriesdata)
			accessoriesdata = (row[1])
			listaccessories.add(accessoriesdata)
			accessoriesdata = (row[2])
			listaccessories.add(accessoriesdata)
			accessoriesdata = (row[3])
			listaccessories.add(accessoriesdata)
			accessoriesdata = (row[4])
			listaccessories.add(accessoriesdata)
			accessoriesdata = (row[5])
			listaccessories.add(accessoriesdata)
			accessoriesdata = (row[6])
			listaccessories.add(accessoriesdata)
			accessoriesdata = (row[7])
			listaccessories.add(accessoriesdata)
		})
		return listaccessories
	}

	@Keyword
	public NAP2InsuranceCMStoreDB (Sql instance, String appno){
		String insurancedata
		instance.eachRow(("SELECT c.CUST_INSCO_BRANCH_NAME AS HEADER, CONVERT(INT , c.CUST_CVG_AMT) AS HEADER, c.INS_POLICY_NO AS HEADER, c.INS_POLICY_NAME AS HEADER,FORMAT(c.CUST_COVER_START_DT, 'MM/dd/yyyy') AS HEADER, FORMAT(c.END_DT, 'MM/dd/yyyy') AS HEADER, c.CUST_NOTES AS HEADER, c.INS_ASSET_REGION AS HEADER, CONVERT(INT , c.CVG_AMT) AS HEADER, f.REF_MASTER_NAME AS HEADER, c.MR_INS_PAY_METHOD_CODE AS HEADER, c.INSCO_BRANCH_NAME AS HEADER, c.NOTES AS HEADER, c.INS_LENGTH AS HEADER, CONVERT(INT, c.CUST_ADMIN_FEE_AMT) AS HEADER, CONVERT(INT, c.CUST_STAMP_DUTY_FEE) AS HEADER, d.MR_MAIN_CVG_TYPE_CODE AS HEADER, IS_CAPITALIZED AS HEADER, CONVERT(INT, TOTAL_INS_CPTLZ_AMT) AS HEADER, CONVERT(INT, e.SUM_INSURED_AMT) AS HEADER, CONVERT(INT, e.CUST_ADD_PREMI_AMT) AS HEADER, CONVERT(INT, TOTAL_CUST_FEE_AMT) AS HEADER, CONVERT(INT , a.TOTAL_CUST_DISC_AMT) AS HEADER, CONVERT(INT, TOTAL_PREMI_PAID_BY_CUST_AMT) AS HEADER FROM APP_INS a JOIN APP b ON a.APP_ID = b.APP_ID JOIN APP_INS_OBJ c ON b.APP_ID = c.APP_ID JOIN APP_INS_MAIN_CVG d ON d.APP_INS_OBJ_ID = c.APP_INS_OBJ_ID JOIN APP_INS_ADD_CVG e ON e.APP_INS_MAIN_CVG_ID = d.APP_INS_MAIN_CVG_ID JOIN REF_MASTER_LOS f ON f.REF_MASTER_CODE = c.INS_ASSET_COVER_PERIOD WHERE APP_NO = '"+ appno +"'"), {  row ->

			insurancedata = (row)
		})
		return insurancedata
	}


	@Keyword
	public NAP2InsuranceCStoreDB (Sql instance, String appno){
		String insurancedata
		instance.eachRow(("SELECT c.CUST_INSCO_BRANCH_NAME AS HEADER, CONVERT(INT , c.CUST_CVG_AMT) AS HEADER, c.INS_POLICY_NO AS HEADER, c.INS_POLICY_NAME AS HEADER, FORMAT(c.CUST_COVER_START_DT, 'MM/dd/yyyy') AS HEADER, FORMAT(c.END_DT, 'MM/dd/yyyy') AS HEADER, c.CUST_NOTES AS HEADER  FROM APP_INS a JOIN APP b ON a.APP_ID = b.APP_ID JOIN APP_INS_OBJ c ON b.APP_ID = c.APP_ID WHERE APP_NO = '"+ appno +"'"), {  row ->

			insurancedata = (row)
		})
		return insurancedata
	}

	@Keyword
	public NAP2InsuranceMStoreDB (Sql instance, String appno){
		String insurancedata
		instance.eachRow(("SELECT DISTINCT c.INS_ASSET_REGION AS HEADER, CONVERT(INT , c.CVG_AMT) AS HEADER, f.REF_MASTER_NAME AS HEADER, g.REF_MASTER_NAME AS HEADER, c.INSCO_BRANCH_NAME AS HEADER, c.NOTES AS HEADER, c.INS_LENGTH AS HEADER, CONVERT(INT, c.CUST_ADMIN_FEE_AMT) AS HEADER, CONVERT(INT, c.CUST_STAMP_DUTY_FEE) AS HEADER, h.REF_MASTER_NAME AS HEADER, IS_CAPITALIZED AS HEADER, CONVERT(INT, TOTAL_INS_CPTLZ_AMT) AS HEADER FROM APP_INS a JOIN APP b ON a.APP_ID = b.APP_ID JOIN APP_INS_OBJ c ON b.APP_ID = c.APP_ID JOIN APP_INS_MAIN_CVG d ON d.APP_INS_OBJ_ID = c.APP_INS_OBJ_ID JOIN APP_INS_ADD_CVG e ON e.APP_INS_MAIN_CVG_ID = d.APP_INS_MAIN_CVG_ID JOIN REF_MASTER_LOS f ON f.REF_MASTER_CODE = c.INS_ASSET_COVER_PERIOD JOIN REF_MASTER_LOS g ON g.REF_MASTER_CODE = c.PAY_PERIOD_TO_INSCO JOIN REF_MASTER_LOS h ON h.REF_MASTER_CODE = d.MR_MAIN_CVG_TYPE_CODE WHERE APP_NO = '"+ appno +"' AND g.REF_MASTER_TYPE_CODE = 'PAY_PERIOD_TO_INSCO'"), {  row ->

			insurancedata = (row)
		})
		return insurancedata
	}


	@Keyword
	public NAP2InsuranceCVGStoreDB (Sql instance, String appno){
		String insurancedata
		ArrayList <String> listCVG = new ArrayList<String>()
		instance.eachRow(("SELECT CONVERT(INT, e.SUM_INSURED_AMT) AS HEADER, CONVERT(INT, e.CUST_ADD_PREMI_AMT) AS HEADER, CONVERT(INT, TOTAL_CUST_FEE_AMT) AS HEADER, CONVERT(INT , a.TOTAL_CUST_DISC_AMT) AS HEADER, CONVERT(INT, TOTAL_PREMI_PAID_BY_CUST_AMT) AS HEADER FROM APP_INS a JOIN APP b ON a.APP_ID = b.APP_ID JOIN APP_INS_OBJ c ON b.APP_ID = c.APP_ID JOIN APP_INS_MAIN_CVG d ON d.APP_INS_OBJ_ID = c.APP_INS_OBJ_ID JOIN APP_INS_ADD_CVG e ON e.APP_INS_MAIN_CVG_ID = d.APP_INS_MAIN_CVG_ID JOIN REF_MASTER_LOS f ON f.REF_MASTER_CODE = c.INS_ASSET_COVER_PERIOD JOIN REF_MASTER_LOS g ON g.REF_MASTER_CODE = c.PAY_PERIOD_TO_INSCO JOIN REF_MASTER_LOS h ON h.REF_MASTER_CODE = d.MR_MAIN_CVG_TYPE_CODE WHERE APP_NO = '"+ appno +"'"), {  row ->

			insurancedata = (row[0])
			listCVG.add(insurancedata)
			insurancedata = (row[1])
			listCVG.add(insurancedata)
			insurancedata = (row[2])
			listCVG.add(insurancedata)
			insurancedata = (row[3])
			listCVG.add(insurancedata)
			insurancedata = (row[4])
			listCVG.add(insurancedata)
		})
		return insurancedata
	}


	@Keyword
	public NAP2LifeInsuranceStoreDB (Sql instance, String appno){
		String lifeinsurancedata
		instance.eachRow(("SELECT b.LIFE_INSCO_BRANCH_NAME AS HEADER, d.REF_MASTER_NAME AS HEADER, 100 - CONVERT(int, b.PAID_IN_ADV_PRCNT) AS HEADER, NEW_COVER_NOTES AS HEADER, IS_CUST_COVER AS HEADER, IS_GUARANTOR_COVER AS HEADER, IS_SPOUSE_COVER AS HEADER, CONVERT(INT, CUST_ADMIN_FEE_AMT) AS HEADER FROM APP_LIFE_INS_D a JOIN APP_LIFE_INS_H b ON a.APP_LIFE_INS_H_ID = b.APP_LIFE_INS_H_ID JOIN APP c ON b.APP_ID = c.APP_ID JOIN REF_MASTER_LOS d ON d.REF_MASTER_CODE = b.MR_LIFE_INS_PAID_METHOD_CODE WHERE APP_NO = '"+ appno +"'"), {  row ->

			lifeinsurancedata = (row)
		})
		return lifeinsurancedata
	}

	@Keyword
	public NAP2FinancialStoreDB (Sql instance, String appno){
		String financialdata
		instance.eachRow(("SELECT CONVERT(INT, TOTAL_FEE_AMT) AS HEADER, CONVERT(INT, TOTAL_FEE_CPTLZ_AMT) AS HEADER, c.REF_MASTER_NAME AS HEADER, EFFECTIVE_RATE_PRCNT AS HEADER, FLAT_RATE_PRCNT AS HEADER, GRACE_PERIOD AS HEADER, a.MR_GRACE_PERIOD_TYPE_CODE AS HEADER, CONVERT(INT,TDP_PAID_COY_AMT) AS HEADER FROM APP_FIN_DATA a JOIN APP b ON a.APP_ID = b.APP_ID JOIN REF_MASTER_LOS c ON c.REF_MASTER_CODE = a.MR_PROVISION_FEE_CALC_METHOD_CODE WHERE APP_NO = '"+ appno +"'"), {  row ->

			financialdata = (row)
		})
		return financialdata
	}


	@Keyword
	public NAP2SubsidyStoreDB (Sql instance, String appno){
		String subsidy
		ArrayList <String> listsubsidy = new ArrayList<String>()
		instance.eachRow(("select MR_SUBSIDY_FROM_TYPE_NAME, SUBSIDY_FROM_VALUE_NAME, MR_SUBSIDY_ALLOC_NAME, MR_SUBSIDY_SOURCE_NAME, CONVERT(INT, SUBSIDY_AMT), CONVERT(INT, SUBSIDY_PRCNT) from APP_SUBSIDY a JOIN APP b ON a.APP_ID = b.APP_ID WHERE APP_NO = '"+ appno +"'"), {  row ->

			subsidy = (row[0])
			listsubsidy.add(subsidy)
			subsidy = (row[1])
			listsubsidy.add(subsidy)
			subsidy = (row[2])
			listsubsidy.add(subsidy)
			subsidy = (row[3])
			listsubsidy.add(subsidy)
			subsidy = (row[4])
			listsubsidy.add(subsidy)
			subsidy = (row[5])
			listsubsidy.add(subsidy)
		})
		return listsubsidy
	}

	@Keyword
	public NAP2TermConditionStoreDB (Sql instance, String appno){
		String termandcondition
		ArrayList <String> listTC = new ArrayList<String>()
		instance.eachRow(("SELECT IS_CHECKED, FORMAT(PROMISED_DT, 'MM/dd/yyy'), FORMAT(EXPIRED_DT, 'MM/dd/yyyy'), IS_WAIVED FROM APP_TC a JOIN APP b ON a.APP_ID = b.APP_ID WHERE APP_NO = '"+ appno +"'"), {  row ->

			termandcondition = (row[0])
			listTC.add(termandcondition)
			termandcondition = (row[1])
			listTC.add(termandcondition)
			termandcondition = (row[2])
			listTC.add(termandcondition)
			termandcondition = (row[3])
			listTC.add(termandcondition)
		})
		return listTC
	}


	@Keyword
	public NAP3CommissionDataStoreDB(Sql instance, String appno, String allocationType){
		HashMap<String, ArrayList> result = new HashMap<>()
		ArrayList<String> resultSupp = new ArrayList<String>()
		ArrayList<String> resultSuppEmp = new ArrayList<String>()
		ArrayList<String> resultRef = new ArrayList<String>()

		if(allocationType.equalsIgnoreCase("Amount")){
			instance.eachRow(("SELECT COMMISSION_RECIPIENT_REF_NO, MR_COMMISSION_SOURCE_CODE, COMMISSION_AMT, REFUND_AMT FROM APP_COMMISSION_H a JOIN APP_COMMISSION_D b ON b.APP_COMMISSION_H_ID = a.APP_COMMISSION_H_ID WHERE APP_id = (Select app_id from app where app_no = '"+appno+"') and MR_COMMISSION_RECIPIENT_TYPE_CODE = 'SUPPLIER'"), {  row ->
				if(row[3]==0.00){
					resultSupp.add("-1")
				}
				else{
					resultSupp.add(row[2])
				}
			})
			instance.eachRow(("SELECT COMMISSION_RECIPIENT_REF_NO, MR_COMMISSION_SOURCE_CODE, COMMISSION_AMT, REFUND_AMT FROM APP_COMMISSION_H a JOIN APP_COMMISSION_D b ON b.APP_COMMISSION_H_ID = a.APP_COMMISSION_H_ID WHERE APP_id = (Select app_id from app where app_no = '"+appno+"') and MR_COMMISSION_RECIPIENT_TYPE_CODE = 'SUPPLIER_EMP'"), {  row ->
				if(row[3]==0.00){
					resultSuppEmp.add("-1")
				}
				else{
					resultSuppEmp.add(row[2])
				}
			})
			instance.eachRow(("SELECT COMMISSION_RECIPIENT_REF_NO, MR_COMMISSION_SOURCE_CODE, COMMISSION_AMT, REFUND_AMT FROM APP_COMMISSION_H a JOIN APP_COMMISSION_D b ON b.APP_COMMISSION_H_ID = a.APP_COMMISSION_H_ID WHERE APP_id = (Select app_id from app where app_no = '"+appno+"') and MR_COMMISSION_RECIPIENT_TYPE_CODE = 'REFERANTOR'"), {  row ->
				if(row[3]==0.00){
					resultRef.add("-1")
				}
				else{
					resultRef.add(row[2])
				}
			})
		}
		else if(allocationType.equalsIgnoreCase("Percentage")){
			instance.eachRow(("SELECT COMMISSION_RECIPIENT_REF_NO, MR_COMMISSION_SOURCE_CODE, CASE WHEN (COMMISSION_AMT/NULLIF(REFUND_AMT, 0))*100 IS NULL THEN 0 ELSE (COMMISSION_AMT/NULLIF(REFUND_AMT, 0))*100 END, REFUND_AMT FROM APP_COMMISSION_H a JOIN APP_COMMISSION_D b ON b.APP_COMMISSION_H_ID = a.APP_COMMISSION_H_ID WHERE APP_id = (Select app_id from app where app_no = '"+appno+"') and MR_COMMISSION_RECIPIENT_TYPE_CODE = 'SUPPLIER'"), {  row ->

				if(row[3]==0.00){
					resultSupp.add("-1")
				}
				else{
					resultSupp.add(row[2])
				}
			})
			instance.eachRow(("SELECT COMMISSION_RECIPIENT_REF_NO, MR_COMMISSION_SOURCE_CODE, CASE WHEN (COMMISSION_AMT/NULLIF(REFUND_AMT, 0))*100 IS NULL THEN 0 ELSE (COMMISSION_AMT/NULLIF(REFUND_AMT, 0))*100 END, REFUND_AMT FROM APP_COMMISSION_H a JOIN APP_COMMISSION_D b ON b.APP_COMMISSION_H_ID = a.APP_COMMISSION_H_ID WHERE APP_id = (Select app_id from app where app_no = '"+appno+"') and MR_COMMISSION_RECIPIENT_TYPE_CODE = 'SUPPLIER_EMP'"), {  row ->

				if(row[3]==0.00){
					resultSuppEmp.add("-1")
				}
				else{
					resultSuppEmp.add(row[2])
				}
			})
			instance.eachRow(("SELECT COMMISSION_RECIPIENT_REF_NO, MR_COMMISSION_SOURCE_CODE, CASE WHEN (COMMISSION_AMT/NULLIF(REFUND_AMT, 0))*100 IS NULL THEN 0 ELSE (COMMISSION_AMT/NULLIF(REFUND_AMT, 0))*100 END, REFUND_AMT FROM APP_COMMISSION_H a JOIN APP_COMMISSION_D b ON b.APP_COMMISSION_H_ID = a.APP_COMMISSION_H_ID WHERE APP_id = (Select app_id from app where app_no = '"+appno+"') and MR_COMMISSION_RECIPIENT_TYPE_CODE = 'REFERANTOR'"), {  row ->

				if(row[3]==0.00){
					resultRef.add("-1")
				}
				else{
					resultRef.add(row[2])
				}
			})
		}

		result.put("Supp",resultSupp)
		result.put("SuppEmp",resultSuppEmp)
		result.put("Ref",resultRef)
		return result
	}


	@Keyword
	public countCommissionRecipientDB(Sql instance, String appno){
		ArrayList<Integer> listcount = new ArrayList<>()
		instance.eachRow(("SELECT 'SUPPLIER' AS HEADER, COUNT(*) AS HEADER FROM APP_COMMISSION_H WHERE APP_id = (Select app_id from app where app_no = '"+appno+"') AND MR_COMMISSION_RECIPIENT_TYPE_CODE = 'SUPPLIER' UNION SELECT 'SUPPLIER_EMP' AS HEADER, COUNT(*) AS HEADER FROM APP_COMMISSION_H WHERE APP_id = (Select app_id from app where app_no = '"+appno+"') AND MR_COMMISSION_RECIPIENT_TYPE_CODE = 'SUPPLIER_EMP' UNION SELECT 'REFERANTOR' AS HEADER, COUNT(*) AS HEADER FROM APP_COMMISSION_H WHERE APP_id = (Select app_id from app where app_no = '"+appno+"') AND MR_COMMISSION_RECIPIENT_TYPE_CODE = 'REFERANTOR'"), {  row ->
			listcount.add(row[1])
		})
		return listcount
	}

	@Keyword
	public countCommissionSourceSupplierDB(Sql instance, String appno){
		Integer countCS
		instance.eachRow(("SELECT a.APP_COMMISSION_H_ID, COMMISSION_RECIPIENT_REF_NO, COUNT(*) AS HEADER FROM APP_COMMISSION_H a JOIN APP_COMMISSION_D b ON b.APP_COMMISSION_H_ID = a.APP_COMMISSION_H_ID WHERE APP_id = (Select app_id from app where app_no = '"+appno+"') and MR_COMMISSION_RECIPIENT_TYPE_CODE = 'SUPPLIER' GROUP BY COMMISSION_RECIPIENT_REF_NO, a.APP_COMMISSION_H_ID ORDER BY a.APP_COMMISSION_H_ID"), {  row ->
			countCS = row[2]
		})
		return countCS
	}

	@Keyword
	public countCommissionSourceSupplierEmpDB(Sql instance, String appno){
		ArrayList<Integer> countCS = new ArrayList<>()
		instance.eachRow(("SELECT a.APP_COMMISSION_H_ID, COMMISSION_RECIPIENT_REF_NO, COUNT(MR_COMMISSION_SOURCE_CODE) AS HEADER FROM APP_COMMISSION_H a JOIN APP_COMMISSION_D b ON b.APP_COMMISSION_H_ID = a.APP_COMMISSION_H_ID WHERE APP_id = (Select app_id from app where app_no = '"+appno+"') and MR_COMMISSION_RECIPIENT_TYPE_CODE = 'SUPPLIER_EMP' GROUP BY COMMISSION_RECIPIENT_REF_NO, a.APP_COMMISSION_H_ID ORDER BY a.APP_COMMISSION_H_ID"), {  row ->
			println(row[2])
			countCS.add(row[2])
		})
		return countCS
	}

	@Keyword
	public countCommissionSourceReferantorDB(Sql instance, String appno){
		ArrayList<Integer> countCS = new ArrayList<>()
		instance.eachRow(("SELECT a.APP_COMMISSION_H_ID, COMMISSION_RECIPIENT_REF_NO, COUNT(MR_COMMISSION_SOURCE_CODE) AS HEADER FROM APP_COMMISSION_H a JOIN APP_COMMISSION_D b ON b.APP_COMMISSION_H_ID = a.APP_COMMISSION_H_ID WHERE APP_id = (Select app_id from app where app_no = '"+appno+"') and MR_COMMISSION_RECIPIENT_TYPE_CODE = 'REFERANTOR' GROUP BY COMMISSION_RECIPIENT_REF_NO, a.APP_COMMISSION_H_ID ORDER BY a.APP_COMMISSION_H_ID"), {  row ->
			countCS.add(row[2])
		})
		return countCS
	}


	@Keyword
	public NAP3ReservedFundDataStoreDB(Sql instance, String appno){
		ArrayList<String> rsvAmt = new ArrayList<>()
		instance.eachRow(("select reserved_fund_amt from app_reserved_fund where app_id = (select app_id from app where app_no='"+appno+"')"), {  row ->
			rsvAmt.add(row[0])
		})
		return rsvAmt
	}
}
