<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Edit</name>
   <tag></tag>
   <elementGuidId>fdc122f6-f923-4bb0-b1b2-bb97cb56aff7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;FinData_Subsidy&quot;]/div[2]/table/tbody/tr/td[8]/a[1]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;FinData_Subsidy&quot;]/div[2]/table/tbody/tr/td[8]/a[1]/i</value>
   </webElementProperties>
</WebElementEntity>
