<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FromTypeName</name>
   <tag></tag>
   <elementGuidId>c3cb7ee9-8225-496d-9b97-21597f551ae0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;FinData_Subsidy&quot;]/div[2]/table/tbody/tr/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;FinData_Subsidy&quot;]/div[2]/table/tbody/tr/td[1]</value>
   </webElementProperties>
</WebElementEntity>
