<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Fee3</name>
   <tag></tag>
   <elementGuidId>ceded85f-2e82-44a4-ab41-bf8cf836c863</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;FinData_Fees&quot;]/form/div/div/div[1]/div[3]/div/div[1]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;FinData_Fees&quot;]/form/div/div/div[1]/div[3]/div/div[1]/label</value>
   </webElementProperties>
</WebElementEntity>
