<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AllocationFromSupplier</name>
   <tag></tag>
   <elementGuidId>1a3c04f7-1204-4331-bfb4-9062ec4e087d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/ngb-modal-window/div/div/app-subsidy-add-edit/form/div[2]/div/div[3]/div/select</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[@id='result'][@formcontrolname=&quot;allocCode&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='result'][@formcontrolname=&quot;allocCode&quot;]</value>
   </webElementProperties>
</WebElementEntity>
