<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubsidyValueType</name>
   <tag></tag>
   <elementGuidId>a1969de3-7ed0-4960-a661-0cb25f155427</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;FinData_Subsidy&quot;]/div[2]/table/tbody/tr/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;FinData_Subsidy&quot;]/div[2]/table/tbody/tr/td[4]</value>
   </webElementProperties>
</WebElementEntity>
