<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubsidyAllocation</name>
   <tag></tag>
   <elementGuidId>3e2d09c1-f2ca-425c-9e93-1dc4354b0839</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;FinData_Subsidy&quot;]/div[2]/table/tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;FinData_Subsidy&quot;]/div[2]/table/tbody/tr/td[3]</value>
   </webElementProperties>
</WebElementEntity>
