<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TotalInsurance</name>
   <tag></tag>
   <elementGuidId>a6cc5032-c59d-4d97-b24e-20d6216e84da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;totalPremi&quot;]/div[6]/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;totalPremi&quot;]/div[6]/label[2]</value>
   </webElementProperties>
</WebElementEntity>
