<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AdmFeeCust</name>
   <tag></tag>
   <elementGuidId>33d0c622-b0af-4c1e-9ee0-17802183dd86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;AppLifeInsId&quot;]/div/div[5]/span/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;AppLifeInsId&quot;]/div/div[5]/span/div/div[2]</value>
   </webElementProperties>
</WebElementEntity>
