<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CoverLifeInsurance</name>
   <tag></tag>
   <elementGuidId>15fb0626-3766-4f82-bad7-5a68da8707b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;AppLifeInsId&quot;]/div/div[1]/span/div/div[2]/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;AppLifeInsId&quot;]/div/div[1]/span/div/div[2]/span/label</value>
   </webElementProperties>
</WebElementEntity>
