<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CptlzPremi</name>
   <tag></tag>
   <elementGuidId>26e87497-522e-470b-91af-b6e788e455c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;AppLifeInsId&quot;]/div/div[7]/span/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;AppLifeInsId&quot;]/div/div[7]/span/div/div[2]</value>
   </webElementProperties>
</WebElementEntity>
