<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LifeInsuranceCompany</name>
   <tag></tag>
   <elementGuidId>78280ecc-73b8-470c-b564-b7e2acac0937</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;AppLifeInsId&quot;]/div/div[2]/span/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;AppLifeInsId&quot;]/div/div[2]/span/div/div[2]</value>
   </webElementProperties>
</WebElementEntity>
