<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PremiInsco</name>
   <tag></tag>
   <elementGuidId>fcf5b1b9-56d3-439d-9f3c-65c18faa5e8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;AppLifeInsId&quot;]/div/div[4]/span/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;AppLifeInsId&quot;]/div/div[4]/span/div/div[2]</value>
   </webElementProperties>
</WebElementEntity>
