<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttondelete</name>
   <tag></tag>
   <elementGuidId>aa6727b5-4da4-40a6-9f5b-322946857a9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;CustomerAssetSection&quot;]/div[2]/table/tbody/tr/td[7]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;CustomerAssetSection&quot;]/div[2]/table/tbody/tr/td[7]/a/i</value>
   </webElementProperties>
</WebElementEntity>
