<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_selectApplicationInprocessCompany</name>
   <tag></tag>
   <elementGuidId>0a6cb221-09dd-40e2-9c1f-719b7354f792</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;subSecAppProcess&quot;]/table/tbody/tr[1]/td[5]/a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;subSecAppProcess&quot;]/table/tbody/tr[1]/td[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;subSecAppProcess&quot;]/table/tbody/tr[1]/td[5]/a</value>
   </webElementProperties>
</WebElementEntity>
