<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tr_CustomerNoSimilarData</name>
   <tag></tag>
   <elementGuidId>8e9e4b38-ee8f-4aa0-8243-70574b3d1f84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;subSecMatch&quot;]/table/tbody/tr[1]/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;subSecMatch&quot;]/table/tbody/tr[1]/td[1]</value>
   </webElementProperties>
</WebElementEntity>
