<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AssetReg</name>
   <tag></tag>
   <elementGuidId>df20e2fd-5fc0-4f1d-814c-2761964c7944</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/ngb-modal-window/div/div/app-app-insurance-detail/div[2]/div/div[2]/div/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ngb-modal-window/div/div/app-app-insurance-detail/div[2]/div/div[2]/div/label[2]</value>
   </webElementProperties>
</WebElementEntity>
