<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CvgAmt</name>
   <tag></tag>
   <elementGuidId>95c827e5-2330-487e-9d79-781e8eb76392</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/ngb-modal-window/div/div/app-app-insurance-detail/div[2]/div/div[4]/div[1]/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ngb-modal-window/div/div/app-app-insurance-detail/div[2]/div/div[4]/div[1]/label[2]</value>
   </webElementProperties>
</WebElementEntity>
