<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FirstInstType</name>
   <tag></tag>
   <elementGuidId>311e264f-99e7-4f0e-825f-2cca1c0a30c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-tab-content-0-7&quot;]/div/view-financial/div/div[5]/div[2]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-tab-content-0-7&quot;]/div/view-financial/div/div[5]/div[2]/div/div[2]</value>
   </webElementProperties>
</WebElementEntity>
