<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LTV</name>
   <tag></tag>
   <elementGuidId>d38d99ab-5030-4c8a-9489-03986207fc61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-tab-content-0-7&quot;]/div/view-financial/div/div[7]/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-tab-content-0-7&quot;]/div/view-financial/div/div[7]/div/div/div[2]</value>
   </webElementProperties>
</WebElementEntity>
