<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ModifyFee</name>
   <tag></tag>
   <elementGuidId>7950d9ac-f4ad-4c93-9454-aa6372a4b939</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;fee&quot;]/div/div[1]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;fee&quot;]/div/div[1]/div/div[2]</value>
   </webElementProperties>
</WebElementEntity>
