<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NumofInst</name>
   <tag></tag>
   <elementGuidId>d41ac568-c6ee-42b1-8492-8d1e22593f6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-tab-content-0-7&quot;]/div/view-financial/div/div[5]/div[8]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-tab-content-0-7&quot;]/div/view-financial/div/div[5]/div[8]/div/div[2]</value>
   </webElementProperties>
</WebElementEntity>
