<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TDPPaidAtMF</name>
   <tag></tag>
   <elementGuidId>e8c7bd09-a663-4c39-9e27-f71c5be25819</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-tab-content-0-7&quot;]/div/view-financial/div/div[4]/div[2]/div/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-tab-content-0-7&quot;]/div/view-financial/div/div[4]/div[2]/div/div[4]</value>
   </webElementProperties>
</WebElementEntity>
