<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TotalFeeCap</name>
   <tag></tag>
   <elementGuidId>59e75468-0d16-4f99-a600-89032adcc765</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;financialData&quot;]/div/div[4]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;financialData&quot;]/div/div[4]/div/div[2]</value>
   </webElementProperties>
</WebElementEntity>
