<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TotalInsuranceCap</name>
   <tag></tag>
   <elementGuidId>cea683c3-f896-495f-82de-e80cb20ffdaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;financialData&quot;]/div/div[6]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;financialData&quot;]/div/div[6]/div/div[2]</value>
   </webElementProperties>
</WebElementEntity>
