<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TotalAssetPrice</name>
   <tag></tag>
   <elementGuidId>b6bb0d7c-3c36-4fe4-af34-133df013cc09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;financialData&quot;]/div/div[1]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;financialData&quot;]/div/div[1]/div/div[2]</value>
   </webElementProperties>
</WebElementEntity>
