<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TotalInterest</name>
   <tag></tag>
   <elementGuidId>8d73cbd3-59a9-4631-9c60-33a117178dfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-tab-content-0-7&quot;]/div/view-financial/div/div[6]/div[1]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-tab-content-0-7&quot;]/div/view-financial/div/div[6]/div[1]/div/div[2]</value>
   </webElementProperties>
</WebElementEntity>
