<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CustomerName</name>
   <tag></tag>
   <elementGuidId>5b9d9f9c-c1e8-4aa9-9f12-2f0f6363aac3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;CustCompanyMainDataId&quot;]/div/div[1]/span/div/div[2]/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;CustCompanyMainDataId&quot;]/div/div[1]/span/div/div[2]/span/label</value>
   </webElementProperties>
</WebElementEntity>
