<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Received</name>
   <tag></tag>
   <elementGuidId>8d81cebd-7fa9-48dd-b6b1-b03d0c1e3e85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;AddAssetDocument&quot;]/div/table/tbody/tr[1]/td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;AddAssetDocument&quot;]/div/table/tbody/tr[1]/td[2]/input</value>
   </webElementProperties>
</WebElementEntity>
