<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AccName</name>
   <tag></tag>
   <elementGuidId>cc3e6229-0993-4203-8404-5c3ad087d9f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;accessoriesData&quot;]/div[2]/table/tbody/tr/td[3]/lib-uclookupgeneric/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;accessoriesData&quot;]/div[2]/table/tbody/tr/td[3]/lib-uclookupgeneric/div/div/input</value>
   </webElementProperties>
</WebElementEntity>
