<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ExpiredDate</name>
   <tag></tag>
   <elementGuidId>295fc7b8-f69b-445c-ac5d-c38d31a3b7cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;AddAssetDocument&quot;]/div/table/tbody/tr[1]/td[4]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;AddAssetDocument&quot;]/div/table/tbody/tr[1]/td[4]/input</value>
   </webElementProperties>
</WebElementEntity>
