<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_supplierAccName</name>
   <tag></tag>
   <elementGuidId>61b6165f-b028-4365-ba5d-8e4b8bac60ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;accessoriesData&quot;]/div[2]/table/tbody/tr/td[2]/lib-uclookupgeneric/div/div/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;accessoriesData&quot;]/div[2]/table/tbody/tr/td[2]/lib-uclookupgeneric/div/div/input</value>
   </webElementProperties>
</WebElementEntity>
