<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_totalSupplier</name>
   <tag></tag>
   <elementGuidId>c323e4b5-7c73-4f08-b4ff-dafcbf0982f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/ngb-modal-window/div/div/div[2]/lib-ucpaging/div/lib-ucgridfooter/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ngb-modal-window/div/div/div[2]/lib-ucpaging/div/lib-ucgridfooter/div/div[3]</value>
   </webElementProperties>
</WebElementEntity>
