<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TableAccessoriesnodata</name>
   <tag></tag>
   <elementGuidId>22c952c9-4102-4c33-99d7-81fa378b8590</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;accessoriesData&quot;]/div[2]/table/tbody/tr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;accessoriesData&quot;]/div[2]/table/tbody/tr</value>
   </webElementProperties>
</WebElementEntity>
