<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_StartWorkingDate</name>
   <tag></tag>
   <elementGuidId>99bca44e-2e72-445b-ae26-c8863bb2dc30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;jobData&quot;]/div[6]/div[2]/div/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;jobData&quot;]/div[6]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;jobData&quot;]/div[6]/div[2]/div/input</value>
   </webElementProperties>
</WebElementEntity>
