<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Kecamatan</name>
   <tag></tag>
   <elementGuidId>b2a6f49a-ab18-467f-b869-4357d105b9cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;Address&quot;]/div/div[1]/div[3]/div[3]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;Address&quot;]/div/div[1]/div[3]/div[3]/div/input</value>
   </webElementProperties>
</WebElementEntity>
