<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelKecamatanAssetOwner</name>
   <tag></tag>
   <elementGuidId>0feace67-bf43-4126-a9a1-e3909790156c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ownerData&quot;]/div/div[2]/div/div[3]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ownerData&quot;]/div/div[2]/div/div[3]/div/input</value>
   </webElementProperties>
</WebElementEntity>
