<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelKelurahanAssetOwner</name>
   <tag></tag>
   <elementGuidId>000c3a0e-7dac-48bb-8a4a-4060ec8437f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ownerData&quot;]/div/div[2]/div/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ownerData&quot;]/div/div[2]/div/div[2]/div/input</value>
   </webElementProperties>
</WebElementEntity>
