<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_AssetDocument</name>
   <tag></tag>
   <elementGuidId>fda39c0f-e2be-4182-91b7-81e43277167f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;AddAssetDocument&quot;]/div/table/tbody/tr[1]/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;AddAssetDocument&quot;]/div/table/tbody/tr[1]/td[1]</value>
   </webElementProperties>
</WebElementEntity>
