<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonDelete</name>
   <tag></tag>
   <elementGuidId>a5369bae-ef56-45fd-9392-d7c2250d89cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;family-tab&quot;]/app-family-main-data-paging/div/div[2]/lib-ucgridview/div/table/tbody/tr[1]/td[6]/span/span[2]/span/span/span/span/span/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;family-tab&quot;]/app-family-main-data-paging/div/div[2]/lib-ucgridview/div/table/tbody/tr[1]/td[6]/span/span[2]/span/span/span/span/span/a/i</value>
   </webElementProperties>
</WebElementEntity>
