<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CheckboxReferantor</name>
   <tag></tag>
   <elementGuidId>5be09484-7170-4d94-a33e-2d6b45e61991</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;Referantor&quot;]/div/div/mat-checkbox/label/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;Referantor&quot;]/div/div/mat-checkbox/label/span[1]</value>
   </webElementProperties>
</WebElementEntity>
