<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IDNoPersonal</name>
   <tag></tag>
   <elementGuidId>d3d0e0c0-e335-49a7-b9d8-5cd9034ac02f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;subSecAppProcess&quot;]/table/tbody/tr[1]/td[4]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;subSecAppProcess&quot;]/table/tbody/tr[1]/td[4]</value>
   </webElementProperties>
</WebElementEntity>
