<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tr_CustomerNo</name>
   <tag></tag>
   <elementGuidId>876cde95-36ba-432a-a1f6-aa0f3b80db53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ListSubjId&quot;]/lib-ucgridview/div/table/tbody/tr[1]/td[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ListSubjId&quot;]/lib-ucgridview/div/table/tbody/tr[1]/td[5]</value>
   </webElementProperties>
</WebElementEntity>
