<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ChooseRole</name>
   <tag></tag>
   <elementGuidId>12f61a40-3611-456c-8074-2dbccabfbb29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;role-modal&quot;]/app-rolepick/div/form/div[2]/div/button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div[2]/div/mat-dialog-container/app-rolepick/div/form/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;role-modal&quot;]/app-rolepick/div/form/div[2]/div/button</value>
   </webElementProperties>
</WebElementEntity>
