<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>assetregion</name>
   <tag></tag>
   <elementGuidId>3d1c8cc0-d964-4c12-9529-7ab5b0f6ca16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;insuranceObject&quot;]/div/div[2]/div[5]/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;insuranceObject&quot;]/div/div[2]/div[5]/label[2]</value>
   </webElementProperties>
</WebElementEntity>
