<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>insurancepaidby</name>
   <tag></tag>
   <elementGuidId>e7e2a93c-0da0-406b-bed6-9c4573d7bd29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;insuranceObject&quot;]/div/div[2]/div[1]/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;insuranceObject&quot;]/div/div[2]/div[1]/label[2]</value>
   </webElementProperties>
</WebElementEntity>
