<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>totaladditionalpremiforinsco</name>
   <tag></tag>
   <elementGuidId>b30e6af3-22ad-4104-8eed-29ae21e1b485</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;summary&quot;]/div/div[2]/div[2]/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;summary&quot;]/div/div[2]/div[2]/label[2]</value>
   </webElementProperties>
</WebElementEntity>
