<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>totalmainpremifrominsco</name>
   <tag></tag>
   <elementGuidId>8657ed6c-9352-4db2-b889-6064a0f157ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;summary&quot;]/div/div[2]/div[1]/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;summary&quot;]/div/div[2]/div[1]/label[2]</value>
   </webElementProperties>
</WebElementEntity>
