<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>appNo</name>
   <tag></tag>
   <elementGuidId>1b762c65-a398-4c93-9a4a-37bc8d0d71c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-full-layout/div/div[2]/div/div/div/div/app-return-handling-paging/lib-ucpaging/lib-ucgridview/div/table/tbody/tr[1]/td[4]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-full-layout/div/div[2]/div/div/div/div/app-return-handling-paging/lib-ucpaging/lib-ucgridview/div/table/tbody/tr[1]/td[4]/span</value>
   </webElementProperties>
</WebElementEntity>
