<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TaskStatus</name>
   <tag></tag>
   <elementGuidId>6bf19ebd-8009-4eb3-97f4-660155dac0c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;returnInformation&quot;]/div[4]/table/tbody/tr/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;returnInformation&quot;]/div[4]/table/tbody/tr/td[4]</value>
   </webElementProperties>
</WebElementEntity>
