<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonTabApplication</name>
   <tag></tag>
   <elementGuidId>00e5ecea-99d2-4e86-bd24-b6cc8456c951</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;stepperCompany&quot;]/div[1]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;stepperCompany&quot;]/div[1]/div[3]</value>
   </webElementProperties>
</WebElementEntity>
