<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonTabAsset</name>
   <tag></tag>
   <elementGuidId>c5da0a59-2a3f-4a2a-bb64-85228a11a909</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;stepperCompany&quot;]/div[1]/div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;stepperCompany&quot;]/div[1]/div[5]</value>
   </webElementProperties>
</WebElementEntity>
