<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>customerno</name>
   <tag></tag>
   <elementGuidId>14851c07-f1e2-435e-9f59-b20090eea64a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;NewApplication&quot;]/div/div[4]/span/div/div[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;NewApplication&quot;]/div/div[4]/span/div/div[2]</value>
   </webElementProperties>
</WebElementEntity>
