<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ButtonDetail</name>
   <tag></tag>
   <elementGuidId>1b502d0a-17be-4fa3-9853-2da0646e059e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ViewReferantor&quot;]/div/table/tbody/tr[1]/td[8]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ViewReferantor&quot;]/div/table/tbody/tr[1]/td[8]/a/i</value>
   </webElementProperties>
</WebElementEntity>
