<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ButtonCancelView</name>
   <tag></tag>
   <elementGuidId>0e68cca6-adcd-461d-817b-fc7f94c32448</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-tab-referantor-multi-detail/div[@class=&quot;modal-footer&quot;]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-tab-referantor-multi-detail/div[@class=&quot;modal-footer&quot;]/button</value>
   </webElementProperties>
</WebElementEntity>
