<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelnodata</name>
   <tag></tag>
   <elementGuidId>04aac43b-146f-4fea-901e-0156249cf04f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;legal-tab&quot;]/app-legal-doc-tab/div/div[2]/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;legal-tab&quot;]/app-legal-doc-tab/div/div[2]/table/tbody/tr/td</value>
   </webElementProperties>
</WebElementEntity>
