<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SelectMatchSimilarDataCompany</name>
   <tag></tag>
   <elementGuidId>1bfa788e-f008-4add-a2a9-614fde6abe52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='subSecMatch']/table/tbody/tr/td[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='subSecMatch']/table/tbody/tr/td[5]/a</value>
   </webElementProperties>
</WebElementEntity>
