<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tr_CustNameAppInProcess</name>
   <tag></tag>
   <elementGuidId>8773485f-f1e6-481b-883e-8cc7a1f02071</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;subSecAppProcess&quot;]/table/tbody/tr[1]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;subSecAppProcess&quot;]/table/tbody/tr[1]/td[2]</value>
   </webElementProperties>
</WebElementEntity>
