<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonBackFamily</name>
   <tag></tag>
   <elementGuidId>18909ffa-44f7-42e6-8d16-b2557c0b3bc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-tab-content-0-0&quot;]/div/app-view-app-cust-data-personal/app-view-app-cust-data-completion-personal/app-view-app-cust-detail/div[1]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-tab-content-0-0&quot;]/div/app-view-app-cust-data-personal/app-view-app-cust-data-completion-personal/app-view-app-cust-detail/div[1]/button</value>
   </webElementProperties>
</WebElementEntity>
