<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ModifyAllocateRef</name>
   <tag></tag>
   <elementGuidId>3d7419b2-1e27-4ed6-80d2-ef1891030c26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;formInformationReferantor&quot;]/div/div[1]/div[3]/div[1]/div/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;formInformationReferantor&quot;]/div/div[1]/div[3]/div[1]/div/div[2]/label</value>
   </webElementProperties>
</WebElementEntity>
