<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ModifySummaryAmt</name>
   <tag></tag>
   <elementGuidId>a0ccf098-070d-4a0a-b494-989e64afec23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;formSummary&quot;]/div/div/div[1]/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;formSummary&quot;]/div/div/div[1]/div[2]/label</value>
   </webElementProperties>
</WebElementEntity>
