<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonTabGuarantor</name>
   <tag></tag>
   <elementGuidId>a1b80117-5ec8-4dc9-b7a9-eb6b147e7d61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;guarantor-tab-trigger&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;guarantor-tab-trigger&quot;]</value>
   </webElementProperties>
</WebElementEntity>
