<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_taskClaimStatus</name>
   <tag></tag>
   <elementGuidId>b02ff581-2d04-474d-bc4f-5633dea6730d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;formSearch&quot;]/div/div/div[1]/div[5]/div/div/div/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;formSearch&quot;]/div/div/div[1]/div[5]/div/div/div/div/select</value>
   </webElementProperties>
</WebElementEntity>
