<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AssetReg</name>
   <tag></tag>
   <elementGuidId>bf2905c3-4c87-4981-b36a-cd34a817085c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;CUCO_Company&quot;]/div[2]/div/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;CUCO_Company&quot;]/div[2]/div/label[2]</value>
   </webElementProperties>
</WebElementEntity>
