<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AssetAttrColor</name>
   <tag></tag>
   <elementGuidId>a49933c3-890e-4455-bea2-99fc24fd5aac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;assetAttr&quot;]/div[1]/div[3]/div/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;assetAttr&quot;]/div[1]/div[3]/div/div[2]/label</value>
   </webElementProperties>
</WebElementEntity>
