<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CollateralUserName</name>
   <tag></tag>
   <elementGuidId>e5629141-b37e-4fdd-8a36-93aede77c57d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;CollUserId&quot;]/div/div[1]/span/div/div[2]/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;CollUserId&quot;]/div/div[1]/span/div/div[2]/span/label</value>
   </webElementProperties>
</WebElementEntity>
