<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CollateralUserRelationship</name>
   <tag></tag>
   <elementGuidId>a15d4083-7c8f-4dce-b82c-6104d542acbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;CollUserId&quot;]/div/div[2]/span/div/div[2]/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;CollUserId&quot;]/div/div[2]/span/div/div[2]/span/label</value>
   </webElementProperties>
</WebElementEntity>
