<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DPPercentAmount</name>
   <tag></tag>
   <elementGuidId>4fb06b65-ba31-41d2-bfc8-60b1af1b5ee8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;asset&quot;]/div[2]/label[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;asset&quot;]/div[2]/label[4]</value>
   </webElementProperties>
</WebElementEntity>
