<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ModifyCollateralAccessories</name>
   <tag></tag>
   <elementGuidId>0e159124-1f45-4501-a638-8e9b54538953</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;collateralAccessories&quot;]/lib-ucgridview/div/table/tbody/tr[1]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;collateralAccessories&quot;]/lib-ucgridview/div/table/tbody/tr[1]/td[2]</value>
   </webElementProperties>
</WebElementEntity>
