<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ModifyCollateralLocation</name>
   <tag></tag>
   <elementGuidId>351b10f8-0dd2-4895-ac14-904b4eb15855</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;LocationId&quot;]/div/div[1]/span/div/div[2]/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;LocationId&quot;]/div/div[1]/span/div/div[2]/span/label</value>
   </webElementProperties>
</WebElementEntity>
