<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SalesPerson</name>
   <tag></tag>
   <elementGuidId>d6eef052-2213-4dad-99dd-a901c6298273</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;supplier&quot;]/div[1]/label[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;supplier&quot;]/div[1]/label[4]</value>
   </webElementProperties>
</WebElementEntity>
