<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WarnaBody</name>
   <tag></tag>
   <elementGuidId>6f63dddf-91a9-45cf-9bff-85197d004d44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;assetAttr&quot;]/div[1]/div[2]/div/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;assetAttr&quot;]/div[1]/div[2]/div/div[2]/label</value>
   </webElementProperties>
</WebElementEntity>
