<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_addBank</name>
   <tag></tag>
   <elementGuidId>eccf4f13-4b54-495c-b964-a29d70a7f68d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;financial-tab&quot;]/app-financial-personal/div/div/div/div/form/app-bank-section/form/span/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;financial-tab&quot;]/app-financial-personal/div/div/div/div/form/app-bank-section/form/span/button</value>
   </webElementProperties>
</WebElementEntity>
