<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CompanyType</name>
   <tag></tag>
   <elementGuidId>bcecbd6c-ed0e-4c13-b79a-7ec6b5381cdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;CustCompanyMainDataId&quot;]/div/div[4]/span/div/div[2]/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;CustCompanyMainDataId&quot;]/div/div[4]/span/div/div[2]/span/label</value>
   </webElementProperties>
</WebElementEntity>
