<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EstablishmentDate</name>
   <tag></tag>
   <elementGuidId>32562632-30b1-43da-a481-ffb17c659e74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;CustCompanyMainDataId&quot;]/div/div[8]/span/div/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;CustCompanyMainDataId&quot;]/div/div[8]/span/div/div[2]/label</value>
   </webElementProperties>
</WebElementEntity>
