<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NPWP</name>
   <tag></tag>
   <elementGuidId>95818feb-b141-4e58-85d0-1b082363700c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;CustCompanyMainDataId&quot;]/div/div[6]/span/div/div[2]/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;CustCompanyMainDataId&quot;]/div/div[6]/span/div/div[2]/span/label</value>
   </webElementProperties>
</WebElementEntity>
