<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_applicationNo</name>
   <tag></tag>
   <elementGuidId>b700550c-c50a-4674-b3b3-023a89603d3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@name=&quot;a.APP_NO&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@name=&quot;a.APP_NO&quot;]</value>
   </webElementProperties>
</WebElementEntity>
