name: Groovy CodeNarc Analysis

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Install Groovy
        run: |
          sudo apt-get update
          sudo apt-get install groovy
          echo "Groovy installed successfully"

      - name: Install Dependencies
        run: |
          echo "Configuring Grape..."
          mkdir -p ~/.groovy
          echo "groovy.grape.report.downloads=true" > ~/.groovy/grapeConfig.xml
          echo "Configured Grape"
          groovy -e "groovy.grape.Grape.grab(group:'commons-cli', module:'commons-cli', version:'1.4')"
          echo "Dependencies installed"

      - name: Run CodeNarc Analysis
        run: |
          groovy /path/to/CodeNarc.groovy
          # Replace /path/to/CodeNarc.groovy with the actual path to your CodeNarc script
        working-directory: ${{ github.workspace }}

      - name: Upload CodeNarc Report
        uses: actions/upload-artifact@v2
        with:
          name: codenarc-report
          path: codenarc-report.xml
