name: Code Scanning

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  code-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Install Groovy
        run: |
          sudo apt-get update
          sudo apt-get install groovy
          echo "Groovy installed successfully"

      - name: Run Grape Dependency Resolution
        run: |
          groovy ./setup.groovy
        working-directory: ${{ github.workspace }}

      - name: Run CodeNarc Analysis on Groovy Scripts
        run: |
          for file in $(find ./Scripts/Login -name "*.groovy"); do
            groovy -cp /path/to/CodeNarc-2.0.0-all.jar -e "import org.codenarc.Main; Main.main(['-basedir', '$file'])"
          done
        working-directory: ${{ github.workspace }}
