name: Katalon Code Scan with Codacy

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
      
jobs:
  code-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Install Groovy
        run: |
          sudo apt-get update
          sudo apt-get install groovy
        working-directory: ${{ github.workspace }}

      - name: Run Katalon Tests
        run: |
          ./path/to/your/katalon.sh -noSplash -runMode=console -consoleLog -projectPath="${{ github.workspace }}/YourKatalonProject.prj" -testSuitePath="Test Suites/YourTestSuite" -apiKey=${{ secrets.KATALON_API_KEY }}
        working-directory: ${{ github.workspace }}

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@main
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          max-allowed-issues: 2147483647

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
